/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	verifyresourceconditionv1 "github.com/IBM/integrity-shield/observer/pkg/apis/verifyresourcecondition/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVerifyResourceConditions implements VerifyResourceConditionInterface
type FakeVerifyResourceConditions struct {
	Fake *FakeApisV1
	ns   string
}

var verifyresourceconditionsResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1", Resource: "verifyresourceconditions"}

var verifyresourceconditionsKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1", Kind: "VerifyResourceCondition"}

// Get takes name of the verifyResourceCondition, and returns the corresponding verifyResourceCondition object, and an error if there is any.
func (c *FakeVerifyResourceConditions) Get(ctx context.Context, name string, options v1.GetOptions) (result *verifyresourceconditionv1.VerifyResourceCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(verifyresourceconditionsResource, c.ns, name), &verifyresourceconditionv1.VerifyResourceCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*verifyresourceconditionv1.VerifyResourceCondition), err
}

// List takes label and field selectors, and returns the list of VerifyResourceConditions that match those selectors.
func (c *FakeVerifyResourceConditions) List(ctx context.Context, opts v1.ListOptions) (result *verifyresourceconditionv1.VerifyResourceConditionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(verifyresourceconditionsResource, verifyresourceconditionsKind, c.ns, opts), &verifyresourceconditionv1.VerifyResourceConditionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &verifyresourceconditionv1.VerifyResourceConditionList{ListMeta: obj.(*verifyresourceconditionv1.VerifyResourceConditionList).ListMeta}
	for _, item := range obj.(*verifyresourceconditionv1.VerifyResourceConditionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested verifyResourceConditions.
func (c *FakeVerifyResourceConditions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(verifyresourceconditionsResource, c.ns, opts))

}

// Create takes the representation of a verifyResourceCondition and creates it.  Returns the server's representation of the verifyResourceCondition, and an error, if there is any.
func (c *FakeVerifyResourceConditions) Create(ctx context.Context, verifyResourceCondition *verifyresourceconditionv1.VerifyResourceCondition, opts v1.CreateOptions) (result *verifyresourceconditionv1.VerifyResourceCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(verifyresourceconditionsResource, c.ns, verifyResourceCondition), &verifyresourceconditionv1.VerifyResourceCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*verifyresourceconditionv1.VerifyResourceCondition), err
}

// Update takes the representation of a verifyResourceCondition and updates it. Returns the server's representation of the verifyResourceCondition, and an error, if there is any.
func (c *FakeVerifyResourceConditions) Update(ctx context.Context, verifyResourceCondition *verifyresourceconditionv1.VerifyResourceCondition, opts v1.UpdateOptions) (result *verifyresourceconditionv1.VerifyResourceCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(verifyresourceconditionsResource, c.ns, verifyResourceCondition), &verifyresourceconditionv1.VerifyResourceCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*verifyresourceconditionv1.VerifyResourceCondition), err
}

// Delete takes name of the verifyResourceCondition and deletes it. Returns an error if one occurs.
func (c *FakeVerifyResourceConditions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(verifyresourceconditionsResource, c.ns, name), &verifyresourceconditionv1.VerifyResourceCondition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVerifyResourceConditions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(verifyresourceconditionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &verifyresourceconditionv1.VerifyResourceConditionList{})
	return err
}

// Patch applies the patch and returns the patched verifyResourceCondition.
func (c *FakeVerifyResourceConditions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *verifyresourceconditionv1.VerifyResourceCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(verifyresourceconditionsResource, c.ns, name, pt, data, subresources...), &verifyresourceconditionv1.VerifyResourceCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*verifyresourceconditionv1.VerifyResourceCondition), err
}
