/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/integrityenforcerpolicy/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/integrityenforcerpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IntegrityEnforcerPoliciesGetter has a method to return a IntegrityEnforcerPolicyInterface.
// A group's client should implement this interface.
type IntegrityEnforcerPoliciesGetter interface {
	IntegrityEnforcerPolicies(namespace string) IntegrityEnforcerPolicyInterface
}

// IntegrityEnforcerPolicyInterface has methods to work with IntegrityEnforcerPolicy resources.
type IntegrityEnforcerPolicyInterface interface {
	Create(*v1alpha1.IntegrityEnforcerPolicy) (*v1alpha1.IntegrityEnforcerPolicy, error)
	Update(*v1alpha1.IntegrityEnforcerPolicy) (*v1alpha1.IntegrityEnforcerPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IntegrityEnforcerPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.IntegrityEnforcerPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IntegrityEnforcerPolicy, err error)
	IntegrityEnforcerPolicyExpansion
}

// integrityEnforcerPolicies implements IntegrityEnforcerPolicyInterface
type integrityEnforcerPolicies struct {
	client rest.Interface
	ns     string
}

// newIntegrityEnforcerPolicies returns a IntegrityEnforcerPolicies
func newIntegrityEnforcerPolicies(c *ResearchV1alpha1Client, namespace string) *integrityEnforcerPolicies {
	return &integrityEnforcerPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrityEnforcerPolicy, and returns the corresponding integrityEnforcerPolicy object, and an error if there is any.
func (c *integrityEnforcerPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.IntegrityEnforcerPolicy, err error) {
	result = &v1alpha1.IntegrityEnforcerPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrityEnforcerPolicies that match those selectors.
func (c *integrityEnforcerPolicies) List(opts v1.ListOptions) (result *v1alpha1.IntegrityEnforcerPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrityEnforcerPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrityEnforcerPolicies.
func (c *integrityEnforcerPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a integrityEnforcerPolicy and creates it.  Returns the server's representation of the integrityEnforcerPolicy, and an error, if there is any.
func (c *integrityEnforcerPolicies) Create(integrityEnforcerPolicy *v1alpha1.IntegrityEnforcerPolicy) (result *v1alpha1.IntegrityEnforcerPolicy, err error) {
	result = &v1alpha1.IntegrityEnforcerPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		Body(integrityEnforcerPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a integrityEnforcerPolicy and updates it. Returns the server's representation of the integrityEnforcerPolicy, and an error, if there is any.
func (c *integrityEnforcerPolicies) Update(integrityEnforcerPolicy *v1alpha1.IntegrityEnforcerPolicy) (result *v1alpha1.IntegrityEnforcerPolicy, err error) {
	result = &v1alpha1.IntegrityEnforcerPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		Name(integrityEnforcerPolicy.Name).
		Body(integrityEnforcerPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the integrityEnforcerPolicy and deletes it. Returns an error if one occurs.
func (c *integrityEnforcerPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrityEnforcerPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched integrityEnforcerPolicy.
func (c *integrityEnforcerPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IntegrityEnforcerPolicy, err error) {
	result = &v1alpha1.IntegrityEnforcerPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrityenforcerpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
