/*
Copyright 2020 IBM Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/vresourceprotectionprofile/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVResourceProtectionProfiles implements VResourceProtectionProfileInterface
type FakeVResourceProtectionProfiles struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var vresourceprotectionprofilesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "vresourceprotectionprofiles"}

var vresourceprotectionprofilesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "VResourceProtectionProfile"}

// Get takes name of the vResourceProtectionProfile, and returns the corresponding vResourceProtectionProfile object, and an error if there is any.
func (c *FakeVResourceProtectionProfiles) Get(name string, options v1.GetOptions) (result *v1alpha1.VResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vresourceprotectionprofilesResource, c.ns, name), &v1alpha1.VResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceProtectionProfile), err
}

// List takes label and field selectors, and returns the list of VResourceProtectionProfiles that match those selectors.
func (c *FakeVResourceProtectionProfiles) List(opts v1.ListOptions) (result *v1alpha1.VResourceProtectionProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vresourceprotectionprofilesResource, vresourceprotectionprofilesKind, c.ns, opts), &v1alpha1.VResourceProtectionProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VResourceProtectionProfileList{ListMeta: obj.(*v1alpha1.VResourceProtectionProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.VResourceProtectionProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vResourceProtectionProfiles.
func (c *FakeVResourceProtectionProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vresourceprotectionprofilesResource, c.ns, opts))

}

// Create takes the representation of a vResourceProtectionProfile and creates it.  Returns the server's representation of the vResourceProtectionProfile, and an error, if there is any.
func (c *FakeVResourceProtectionProfiles) Create(vResourceProtectionProfile *v1alpha1.VResourceProtectionProfile) (result *v1alpha1.VResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vresourceprotectionprofilesResource, c.ns, vResourceProtectionProfile), &v1alpha1.VResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceProtectionProfile), err
}

// Update takes the representation of a vResourceProtectionProfile and updates it. Returns the server's representation of the vResourceProtectionProfile, and an error, if there is any.
func (c *FakeVResourceProtectionProfiles) Update(vResourceProtectionProfile *v1alpha1.VResourceProtectionProfile) (result *v1alpha1.VResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vresourceprotectionprofilesResource, c.ns, vResourceProtectionProfile), &v1alpha1.VResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceProtectionProfile), err
}

// Delete takes name of the vResourceProtectionProfile and deletes it. Returns an error if one occurs.
func (c *FakeVResourceProtectionProfiles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vresourceprotectionprofilesResource, c.ns, name), &v1alpha1.VResourceProtectionProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVResourceProtectionProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vresourceprotectionprofilesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VResourceProtectionProfileList{})
	return err
}

// Patch applies the patch and returns the patched vResourceProtectionProfile.
func (c *FakeVResourceProtectionProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vresourceprotectionprofilesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceProtectionProfile), err
}
