/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	manifestintegritystatev1 "github.com/stolostron/integrity-shield/observer/pkg/apis/manifestintegritystate/v1"
	versioned "github.com/stolostron/integrity-shield/observer/pkg/client/manifestintegritystate/clientset/versioned"
	internalinterfaces "github.com/stolostron/integrity-shield/observer/pkg/client/manifestintegritystate/informers/externalversions/internalinterfaces"
	v1 "github.com/stolostron/integrity-shield/observer/pkg/client/manifestintegritystate/listers/manifestintegritystate/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManifestIntegrityStateInformer provides access to a shared informer and lister for
// ManifestIntegrityStates.
type ManifestIntegrityStateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ManifestIntegrityStateLister
}

type manifestIntegrityStateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManifestIntegrityStateInformer constructs a new informer for ManifestIntegrityState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManifestIntegrityStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManifestIntegrityStateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManifestIntegrityStateInformer constructs a new informer for ManifestIntegrityState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManifestIntegrityStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().ManifestIntegrityStates(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().ManifestIntegrityStates(namespace).Watch(context.TODO(), options)
			},
		},
		&manifestintegritystatev1.ManifestIntegrityState{},
		resyncPeriod,
		indexers,
	)
}

func (f *manifestIntegrityStateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManifestIntegrityStateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *manifestIntegrityStateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&manifestintegritystatev1.ManifestIntegrityState{}, f.defaultInformer)
}

func (f *manifestIntegrityStateInformer) Lister() v1.ManifestIntegrityStateLister {
	return v1.NewManifestIntegrityStateLister(f.Informer().GetIndexer())
}
