apiVersion: apis.integrityverifier.io/v1alpha1
kind: IntegrityVerifier
metadata:
  name: integrity-verifier-server
spec:
  namespace: integrity-verifier-operator-system
  verifierConfig:
    # mode: detect
    log:
      logLevel: trace
    verifyType: pgp # x509
    inScopeNamespaceSelector:
      include:
      - "*"
      exclude:
      - "kube-*"
      - "openshift-*"
  signPolicy:
    policies:
    - namespaces:
      - "*"
      signers:
      - "SampleSigner"
    - scope: "Cluster"
      signers:
      - "SampleSigner"
    signers:
    - name: "SampleSigner"
      secret: keyring-secret
      subjects:
      - email: "hirokuni.kitahara1@ibm.com"
  resourceSigningProfiles:
  - name: sample-rsp
    targetNamespaceSelector:
      include:
      - secure-ns
      - test-ns
    protectRules:
    - match:
      - kind: ConfigMap
    ignoreRules:
    - match:
      - kind: ConfigMap
        name: sample-*
    forceCheckRules:
    - match:
      - kind: ConfigMap
        name: sample-cm
    ignoreAttrs:
    - attrs:
      - data.key2
      match:
      - name: sample-cm
        kind: ConfigMap
  keyRingConfigs:
  - name: keyring-secret
  server:
    image: localhost:5000/integrity-verifier-server:0.0.5dev
    imagePullPolicy: Always
  logger:
    image: localhost:5000/integrity-verifier-logging:0.0.5dev
    imagePullPolicy: Always