apiVersion: apis.integrityshield.io/v1alpha1
kind: IntegrityShield
metadata:
  name: integrity-shield-server
  finalizers:
  - cleanup.finalizers.integrityshield.io
spec:
  # namespace: integrity-shield-operator-system
  shieldConfig:
    inScopeNamespaceSelector:
      include:
      - "*"
      exclude:
      - "kube-*"
      - "openshift-*"
  keyConfig:
  - name: sample-signer-keyconfig
    secretName: keyring-secret