apiVersion: apis.integrityshield.io/v1alpha1
kind: IntegrityShield
metadata:
  name: integrity-shield-server
  finalizers:
  - cleanup.finalizers.integrityshield.io
spec:
  # namespace: integrity-shield-operator-system
  shieldConfig:
    inScopeNamespaceSelector:
      include:
      - "*"
      exclude:
      - "kube-*"
      - "openshift-*"
    sigstoreConfig:
      enabled: true
      useDefaultRootCert: true
    imageVerificationConfig:
      enabled: true
  keyConfig:
  - name: sample-signer-keyconfig
    signatureType: sigstore
  server:
    image: localhost:5000/integrity-shield-server:0.2.0
  logger:
    image: localhost:5000/integrity-shield-logging:0.2.0
  api:
    image: localhost:5000/integrity-shield-api:0.2.0
  controller:
    image: localhost:5000/integrity-shield-controller:0.2.0