//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/protectrule/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProtectRules implements ProtectRuleInterface
type FakeProtectRules struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var protectrulesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "protectrules"}

var protectrulesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "ProtectRule"}

// Get takes name of the protectRule, and returns the corresponding protectRule object, and an error if there is any.
func (c *FakeProtectRules) Get(name string, options v1.GetOptions) (result *v1alpha1.ProtectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(protectrulesResource, c.ns, name), &v1alpha1.ProtectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectRule), err
}

// List takes label and field selectors, and returns the list of ProtectRules that match those selectors.
func (c *FakeProtectRules) List(opts v1.ListOptions) (result *v1alpha1.ProtectRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(protectrulesResource, protectrulesKind, c.ns, opts), &v1alpha1.ProtectRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProtectRuleList{ListMeta: obj.(*v1alpha1.ProtectRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProtectRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested protectRules.
func (c *FakeProtectRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(protectrulesResource, c.ns, opts))

}

// Create takes the representation of a protectRule and creates it.  Returns the server's representation of the protectRule, and an error, if there is any.
func (c *FakeProtectRules) Create(protectRule *v1alpha1.ProtectRule) (result *v1alpha1.ProtectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(protectrulesResource, c.ns, protectRule), &v1alpha1.ProtectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectRule), err
}

// Update takes the representation of a protectRule and updates it. Returns the server's representation of the protectRule, and an error, if there is any.
func (c *FakeProtectRules) Update(protectRule *v1alpha1.ProtectRule) (result *v1alpha1.ProtectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(protectrulesResource, c.ns, protectRule), &v1alpha1.ProtectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectRule), err
}

// Delete takes name of the protectRule and deletes it. Returns an error if one occurs.
func (c *FakeProtectRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(protectrulesResource, c.ns, name), &v1alpha1.ProtectRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProtectRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(protectrulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProtectRuleList{})
	return err
}

// Patch applies the patch and returns the patched protectRule.
func (c *FakeProtectRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ProtectRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(protectrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProtectRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectRule), err
}
