/*
Copyright 2020 IBM Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/signpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSignPolicies implements SignPolicyInterface
type FakeSignPolicies struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var signpoliciesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "signpolicies"}

var signpoliciesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "SignPolicy"}

// Get takes name of the signPolicy, and returns the corresponding signPolicy object, and an error if there is any.
func (c *FakeSignPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.SignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(signpoliciesResource, c.ns, name), &v1alpha1.SignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignPolicy), err
}

// List takes label and field selectors, and returns the list of SignPolicies that match those selectors.
func (c *FakeSignPolicies) List(opts v1.ListOptions) (result *v1alpha1.SignPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(signpoliciesResource, signpoliciesKind, c.ns, opts), &v1alpha1.SignPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SignPolicyList{ListMeta: obj.(*v1alpha1.SignPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.SignPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested signPolicies.
func (c *FakeSignPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(signpoliciesResource, c.ns, opts))

}

// Create takes the representation of a signPolicy and creates it.  Returns the server's representation of the signPolicy, and an error, if there is any.
func (c *FakeSignPolicies) Create(signPolicy *v1alpha1.SignPolicy) (result *v1alpha1.SignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(signpoliciesResource, c.ns, signPolicy), &v1alpha1.SignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignPolicy), err
}

// Update takes the representation of a signPolicy and updates it. Returns the server's representation of the signPolicy, and an error, if there is any.
func (c *FakeSignPolicies) Update(signPolicy *v1alpha1.SignPolicy) (result *v1alpha1.SignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(signpoliciesResource, c.ns, signPolicy), &v1alpha1.SignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignPolicy), err
}

// Delete takes name of the signPolicy and deletes it. Returns an error if one occurs.
func (c *FakeSignPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(signpoliciesResource, c.ns, name), &v1alpha1.SignPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSignPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(signpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SignPolicyList{})
	return err
}

// Patch applies the patch and returns the patched signPolicy.
func (c *FakeSignPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(signpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignPolicy), err
}
