# permissions for end users to view integrityverifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrityverifier-viewer-role
rules:
- apiGroups:
  - apis.integrityverifier.io
  resources:
  - integrityverifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.integrityverifier.io
  resources:
  - integrityverifiers/status
  verbs:
  - get
