# permissions for end users to edit integrityverifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrityverifier-editor-role
rules:
- apiGroups:
  - apis.integrityverifier.io
  resources:
  - integrityverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apis.integrityverifier.io
  resources:
  - integrityverifiers/status
  verbs:
  - get
