apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: new-integrity-shield-operator-catalog
  namespace: openshift-marketplace # olm
spec:
  displayName: Integrity Shield++ Operator
  image: quay.io/stolostron/integrity-shield-operator-index:0.3.1
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m