# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# LOAD ENVIRNOMENT SETTINGS (must be done at first)
###########################
ifeq ($(IE_REPO_ROOT),)
$(error IE_REPO_ROOT is not set)
endif

include  .env
export $(shell sed 's/=.*//' .env)

ifeq ($(ENV_CONFIG),)
$(error ENV_CONFIG is not set)
endif

include  $(ENV_CONFIG)
export $(shell sed 's/=.*//' $(ENV_CONFIG))

include $(VERIFIER_OP_DIR)Makefile

# install integrity verifier
install-server:
	@echo
	@echo deploy cr
	kubectl create -f $(VERIFIER_OP_DIR)test/deploy/apis_v1alpha1_integrityenforcer.yaml -n $(IE_NS)

delete-server:
	@echo
	@echo deploy cr
	kubectl delete -f $(VERIFIER_OP_DIR)test/deploy/apis_v1alpha1_integrityenforcer.yaml -n $(IE_NS)

# install operator
install-operator:
	@echo setting image
	cd $(VERIFIER_OP_DIR)config/manager && kustomize edit set image controller=localhost:5000/$(IV_OPERATOR):$(VERSION)
	@echo installing operator
	kustomize build $(VERIFIER_OP_DIR)config/default | kubectl apply --validate=false -f -

delete-operator:
	@echo deleting operator
	kustomize build $(VERIFIER_OP_DIR)config/default | kubectl delete -f -

# list resourcesigningprofiles
list-rsp:
	kubectl get resourcesigningprofiles.apis.integrityenforcer.io --all-namespaces

# show rule table
show-rt:
	kubectl get cm ie-rule-table-lock -n $(IE_NS) -o json | jq -r .binaryData.table | base64 -D | gzip -d

# show forwarder log
log-f:
	bash ./scripts/watch_events.sh

log-s:
	bash ./scripts/log_server.sh

log-o:
	bash ./scripts/log_operator.sh