apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server
spec:
  selector:
    matchLabels:
      app: sample-server
  template:
    metadata:
      labels:
        app: sample-server
    spec:
      serviceAccountName: sample-server-user
      containers:
      - name: client
        image: localhost:5000/sample-server:latest
        env:
        - name: SHIELD_NS
          value: integrity-shield-operator-system
        - name: SHIELD_CONFIG_NAME
          value: ishield-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /sample-signer-keyconfig/pgp/
          name: sample-signer-keyconfig
      volumes:
      - name: sample-signer-keyconfig
        secret:
          defaultMode: 420
          secretName: sample-server-secret
