---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iv-signing-pipline-admin
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iv-signing-pipline-admin
imagePullSecrets:
  - name: registry-secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iv-signing-pipline-admin-binding
subjects:
  - kind: ServiceAccount
    name: iv-signing-pipline-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iv-signing-pipline-admin
