/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/open-cluster-management/integrity-shield/observer/pkg/apis/manifestintegritystate/v1"
	scheme "github.com/open-cluster-management/integrity-shield/observer/pkg/client/manifestintegritystate/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManifestIntegrityStatesGetter has a method to return a ManifestIntegrityStateInterface.
// A group's client should implement this interface.
type ManifestIntegrityStatesGetter interface {
	ManifestIntegrityStates(namespace string) ManifestIntegrityStateInterface
}

// ManifestIntegrityStateInterface has methods to work with ManifestIntegrityState resources.
type ManifestIntegrityStateInterface interface {
	Create(ctx context.Context, manifestIntegrityState *v1.ManifestIntegrityState, opts metav1.CreateOptions) (*v1.ManifestIntegrityState, error)
	Update(ctx context.Context, manifestIntegrityState *v1.ManifestIntegrityState, opts metav1.UpdateOptions) (*v1.ManifestIntegrityState, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ManifestIntegrityState, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ManifestIntegrityStateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ManifestIntegrityState, err error)
	ManifestIntegrityStateExpansion
}

// manifestIntegrityStates implements ManifestIntegrityStateInterface
type manifestIntegrityStates struct {
	client rest.Interface
	ns     string
}

// newManifestIntegrityStates returns a ManifestIntegrityStates
func newManifestIntegrityStates(c *ApisV1Client, namespace string) *manifestIntegrityStates {
	return &manifestIntegrityStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the manifestIntegrityState, and returns the corresponding manifestIntegrityState object, and an error if there is any.
func (c *manifestIntegrityStates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ManifestIntegrityState, err error) {
	result = &v1.ManifestIntegrityState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManifestIntegrityStates that match those selectors.
func (c *manifestIntegrityStates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ManifestIntegrityStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ManifestIntegrityStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityStates.
func (c *manifestIntegrityStates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a manifestIntegrityState and creates it.  Returns the server's representation of the manifestIntegrityState, and an error, if there is any.
func (c *manifestIntegrityStates) Create(ctx context.Context, manifestIntegrityState *v1.ManifestIntegrityState, opts metav1.CreateOptions) (result *v1.ManifestIntegrityState, err error) {
	result = &v1.ManifestIntegrityState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(manifestIntegrityState).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a manifestIntegrityState and updates it. Returns the server's representation of the manifestIntegrityState, and an error, if there is any.
func (c *manifestIntegrityStates) Update(ctx context.Context, manifestIntegrityState *v1.ManifestIntegrityState, opts metav1.UpdateOptions) (result *v1.ManifestIntegrityState, err error) {
	result = &v1.ManifestIntegrityState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		Name(manifestIntegrityState.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(manifestIntegrityState).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the manifestIntegrityState and deletes it. Returns an error if one occurs.
func (c *manifestIntegrityStates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *manifestIntegrityStates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manifestintegritystates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched manifestIntegrityState.
func (c *manifestIntegrityStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ManifestIntegrityState, err error) {
	result = &v1.ManifestIntegrityState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("manifestintegritystates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
