/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/appenforcepolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppEnforcePolicies implements AppEnforcePolicyInterface
type FakeAppEnforcePolicies struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var appenforcepoliciesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "appenforcepolicies"}

var appenforcepoliciesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "AppEnforcePolicy"}

// Get takes name of the appEnforcePolicy, and returns the corresponding appEnforcePolicy object, and an error if there is any.
func (c *FakeAppEnforcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.AppEnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appenforcepoliciesResource, c.ns, name), &v1alpha1.AppEnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppEnforcePolicy), err
}

// List takes label and field selectors, and returns the list of AppEnforcePolicies that match those selectors.
func (c *FakeAppEnforcePolicies) List(opts v1.ListOptions) (result *v1alpha1.AppEnforcePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appenforcepoliciesResource, appenforcepoliciesKind, c.ns, opts), &v1alpha1.AppEnforcePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AppEnforcePolicyList{ListMeta: obj.(*v1alpha1.AppEnforcePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.AppEnforcePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appEnforcePolicies.
func (c *FakeAppEnforcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appenforcepoliciesResource, c.ns, opts))

}

// Create takes the representation of a appEnforcePolicy and creates it.  Returns the server's representation of the appEnforcePolicy, and an error, if there is any.
func (c *FakeAppEnforcePolicies) Create(appEnforcePolicy *v1alpha1.AppEnforcePolicy) (result *v1alpha1.AppEnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appenforcepoliciesResource, c.ns, appEnforcePolicy), &v1alpha1.AppEnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppEnforcePolicy), err
}

// Update takes the representation of a appEnforcePolicy and updates it. Returns the server's representation of the appEnforcePolicy, and an error, if there is any.
func (c *FakeAppEnforcePolicies) Update(appEnforcePolicy *v1alpha1.AppEnforcePolicy) (result *v1alpha1.AppEnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appenforcepoliciesResource, c.ns, appEnforcePolicy), &v1alpha1.AppEnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppEnforcePolicy), err
}

// Delete takes name of the appEnforcePolicy and deletes it. Returns an error if one occurs.
func (c *FakeAppEnforcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appenforcepoliciesResource, c.ns, name), &v1alpha1.AppEnforcePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppEnforcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appenforcepoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AppEnforcePolicyList{})
	return err
}

// Patch applies the patch and returns the patched appEnforcePolicy.
func (c *FakeAppEnforcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppEnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appenforcepoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AppEnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppEnforcePolicy), err
}
