/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/vresourceprotectionprofile/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/vresourceprotectionprofile/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VResourceProtectionProfilesGetter has a method to return a VResourceProtectionProfileInterface.
// A group's client should implement this interface.
type VResourceProtectionProfilesGetter interface {
	VResourceProtectionProfiles(namespace string) VResourceProtectionProfileInterface
}

// VResourceProtectionProfileInterface has methods to work with VResourceProtectionProfile resources.
type VResourceProtectionProfileInterface interface {
	Create(*v1alpha1.VResourceProtectionProfile) (*v1alpha1.VResourceProtectionProfile, error)
	Update(*v1alpha1.VResourceProtectionProfile) (*v1alpha1.VResourceProtectionProfile, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VResourceProtectionProfile, error)
	List(opts v1.ListOptions) (*v1alpha1.VResourceProtectionProfileList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceProtectionProfile, err error)
	VResourceProtectionProfileExpansion
}

// vResourceProtectionProfiles implements VResourceProtectionProfileInterface
type vResourceProtectionProfiles struct {
	client rest.Interface
	ns     string
}

// newVResourceProtectionProfiles returns a VResourceProtectionProfiles
func newVResourceProtectionProfiles(c *ResearchV1alpha1Client, namespace string) *vResourceProtectionProfiles {
	return &vResourceProtectionProfiles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vResourceProtectionProfile, and returns the corresponding vResourceProtectionProfile object, and an error if there is any.
func (c *vResourceProtectionProfiles) Get(name string, options v1.GetOptions) (result *v1alpha1.VResourceProtectionProfile, err error) {
	result = &v1alpha1.VResourceProtectionProfile{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VResourceProtectionProfiles that match those selectors.
func (c *vResourceProtectionProfiles) List(opts v1.ListOptions) (result *v1alpha1.VResourceProtectionProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VResourceProtectionProfileList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vResourceProtectionProfiles.
func (c *vResourceProtectionProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vResourceProtectionProfile and creates it.  Returns the server's representation of the vResourceProtectionProfile, and an error, if there is any.
func (c *vResourceProtectionProfiles) Create(vResourceProtectionProfile *v1alpha1.VResourceProtectionProfile) (result *v1alpha1.VResourceProtectionProfile, err error) {
	result = &v1alpha1.VResourceProtectionProfile{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		Body(vResourceProtectionProfile).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vResourceProtectionProfile and updates it. Returns the server's representation of the vResourceProtectionProfile, and an error, if there is any.
func (c *vResourceProtectionProfiles) Update(vResourceProtectionProfile *v1alpha1.VResourceProtectionProfile) (result *v1alpha1.VResourceProtectionProfile, err error) {
	result = &v1alpha1.VResourceProtectionProfile{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		Name(vResourceProtectionProfile.Name).
		Body(vResourceProtectionProfile).
		Do().
		Into(result)
	return
}

// Delete takes name of the vResourceProtectionProfile and deletes it. Returns an error if one occurs.
func (c *vResourceProtectionProfiles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vResourceProtectionProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vResourceProtectionProfile.
func (c *vResourceProtectionProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceProtectionProfile, err error) {
	result = &v1alpha1.VResourceProtectionProfile{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vresourceprotectionprofiles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
