apiVersion: apis.integrityverifier.io/v1alpha1
kind: IntegrityVerifier
metadata:
  name: integrity-verifier-server
spec:
  namespace: integrity-verifier-operator-system
  affinity: {}
  resourceSigningProfiles: []
  signPolicy: {}
  verifierConfig:
    verifyType: pgp # x509
    plugin:
    - name: helm
      enabled: false
    ieResource: "apis.integrityverifier.io"
    ivAdminUserName: ""
    ivAdminUserGroup: "system:masters,system:cluster-admins"
    ignore:
    - kind: Event
    - kind: Lease
    - kind: Endpoints
    - kind: TokenReview
    - kind: SubjectAccessReview
    - kind: SelfSubjectAccessReview
    patch:
      enabled: true
    log:
      consoleLog:
        enabled: true
        inScope:
        - kind: '*'
      contextLog:
        enabled: true
        inScope:
        - kind: '*'
      logLevel: info
  verifierConfigCrName: iv-config
  imagePullSecrets: []
  globalConfig: 
    detectionMode: false
  certPoolConfigs:
  - createIfNotExist: false
    keyValue: test
    name: iv-certpool-secret
  keyRingConfigs:
  - createIfNotExist: false
    keyValue: test
    name: keyring-secret
  labels:
    app: iv-server
  logger:
    enabled: true
    es:
      enabled: false
      host: 10.200.10.10
      indexPrefix: ac-log
      port: 9200
      scheme: http
    http:
      enabled: false
      endpoint: http://sample-http-server:8093/api
    esSecretName: es-tls-certs
    image: integrityverifier/integrity-verifier-logging:0.0.4
    imagePullPolicy: Always
    name: forwarder
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    stdOutput: true
  replicaCount: 1
  security:
    clusterRole: iv-cluster-role
    clusterRoleBinding: iv-cluster-role-binding
    podSecurityPolicyName: iv-psp
    securityContextConstraintsName:  iv-scc
    serviceAccountName: iv-sa
    ivAdminSubjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:masters
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:cluster-admins
    autoIVAdminRoleCreationDisabled: false
  selector:
    app: iv-server
  server:
    chartBaseUrl: http://sample-chart-repo-server/charts
    contextLogEnabled: true
    verifierPolicyReloadSec: 10
    image: integrityverifier/integrity-verifier-server:0.0.4
    imagePullPolicy: Always
    name: server
    port: 8443
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext: {}
  webhookConfigName: iv-webhook-config
  webhookServerTlsSecretName: iv-server-tls
  webhookServiceName: iv-server
  webhookNamespacedResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
  webhookClusterResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
    # OCP4.4 or earlier, need to select resources.
    # - podsecuritypolicies
    # - clusterrolebindings
    # - clusterroles
