apiVersion: v1
kind: ConfigMap
metadata:
  name: shield-config
  namespace: k8s-manifest-sigstore
data:
  config.yaml: |
    inScopeNamespaceSelector:
      exclude:
        - kube-*
        - openshift-*
    allow:
      kinds:
      - kind: Event
      - kind: Lease
      - kind: Endpoints
      - kind: TokenReview
      - kind: SubjectAccessReview
      - kind: SelfSubjectAccessReview
