//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/vsignpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVSignPolicies implements VSignPolicyInterface
type FakeVSignPolicies struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var vsignpoliciesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "vsignpolicies"}

var vsignpoliciesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "VSignPolicy"}

// Get takes name of the vSignPolicy, and returns the corresponding vSignPolicy object, and an error if there is any.
func (c *FakeVSignPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.VSignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vsignpoliciesResource, c.ns, name), &v1alpha1.VSignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSignPolicy), err
}

// List takes label and field selectors, and returns the list of VSignPolicies that match those selectors.
func (c *FakeVSignPolicies) List(opts v1.ListOptions) (result *v1alpha1.VSignPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vsignpoliciesResource, vsignpoliciesKind, c.ns, opts), &v1alpha1.VSignPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VSignPolicyList{ListMeta: obj.(*v1alpha1.VSignPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.VSignPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vSignPolicies.
func (c *FakeVSignPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vsignpoliciesResource, c.ns, opts))

}

// Create takes the representation of a vSignPolicy and creates it.  Returns the server's representation of the vSignPolicy, and an error, if there is any.
func (c *FakeVSignPolicies) Create(vSignPolicy *v1alpha1.VSignPolicy) (result *v1alpha1.VSignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vsignpoliciesResource, c.ns, vSignPolicy), &v1alpha1.VSignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSignPolicy), err
}

// Update takes the representation of a vSignPolicy and updates it. Returns the server's representation of the vSignPolicy, and an error, if there is any.
func (c *FakeVSignPolicies) Update(vSignPolicy *v1alpha1.VSignPolicy) (result *v1alpha1.VSignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vsignpoliciesResource, c.ns, vSignPolicy), &v1alpha1.VSignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSignPolicy), err
}

// Delete takes name of the vSignPolicy and deletes it. Returns an error if one occurs.
func (c *FakeVSignPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vsignpoliciesResource, c.ns, name), &v1alpha1.VSignPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVSignPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vsignpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VSignPolicyList{})
	return err
}

// Patch applies the patch and returns the patched vSignPolicy.
func (c *FakeVSignPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VSignPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vsignpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VSignPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSignPolicy), err
}
