/*
Copyright 2020 IBM Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/clusterresourceprotectionprofile/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/clusterresourceprotectionprofile/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterResourceProtectionProfilesGetter has a method to return a ClusterResourceProtectionProfileInterface.
// A group's client should implement this interface.
type ClusterResourceProtectionProfilesGetter interface {
	ClusterResourceProtectionProfiles() ClusterResourceProtectionProfileInterface
}

// ClusterResourceProtectionProfileInterface has methods to work with ClusterResourceProtectionProfile resources.
type ClusterResourceProtectionProfileInterface interface {
	Create(*v1alpha1.ClusterResourceProtectionProfile) (*v1alpha1.ClusterResourceProtectionProfile, error)
	Update(*v1alpha1.ClusterResourceProtectionProfile) (*v1alpha1.ClusterResourceProtectionProfile, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterResourceProtectionProfile, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterResourceProtectionProfileList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterResourceProtectionProfile, err error)
	ClusterResourceProtectionProfileExpansion
}

// clusterResourceProtectionProfiles implements ClusterResourceProtectionProfileInterface
type clusterResourceProtectionProfiles struct {
	client rest.Interface
}

// newClusterResourceProtectionProfiles returns a ClusterResourceProtectionProfiles
func newClusterResourceProtectionProfiles(c *ResearchV1alpha1Client) *clusterResourceProtectionProfiles {
	return &clusterResourceProtectionProfiles{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterResourceProtectionProfile, and returns the corresponding clusterResourceProtectionProfile object, and an error if there is any.
func (c *clusterResourceProtectionProfiles) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterResourceProtectionProfile, err error) {
	result = &v1alpha1.ClusterResourceProtectionProfile{}
	err = c.client.Get().
		Resource("clusterresourceprotectionprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterResourceProtectionProfiles that match those selectors.
func (c *clusterResourceProtectionProfiles) List(opts v1.ListOptions) (result *v1alpha1.ClusterResourceProtectionProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterResourceProtectionProfileList{}
	err = c.client.Get().
		Resource("clusterresourceprotectionprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterResourceProtectionProfiles.
func (c *clusterResourceProtectionProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterresourceprotectionprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterResourceProtectionProfile and creates it.  Returns the server's representation of the clusterResourceProtectionProfile, and an error, if there is any.
func (c *clusterResourceProtectionProfiles) Create(clusterResourceProtectionProfile *v1alpha1.ClusterResourceProtectionProfile) (result *v1alpha1.ClusterResourceProtectionProfile, err error) {
	result = &v1alpha1.ClusterResourceProtectionProfile{}
	err = c.client.Post().
		Resource("clusterresourceprotectionprofiles").
		Body(clusterResourceProtectionProfile).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterResourceProtectionProfile and updates it. Returns the server's representation of the clusterResourceProtectionProfile, and an error, if there is any.
func (c *clusterResourceProtectionProfiles) Update(clusterResourceProtectionProfile *v1alpha1.ClusterResourceProtectionProfile) (result *v1alpha1.ClusterResourceProtectionProfile, err error) {
	result = &v1alpha1.ClusterResourceProtectionProfile{}
	err = c.client.Put().
		Resource("clusterresourceprotectionprofiles").
		Name(clusterResourceProtectionProfile.Name).
		Body(clusterResourceProtectionProfile).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterResourceProtectionProfile and deletes it. Returns an error if one occurs.
func (c *clusterResourceProtectionProfiles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterresourceprotectionprofiles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterResourceProtectionProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterresourceprotectionprofiles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterResourceProtectionProfile.
func (c *clusterResourceProtectionProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterResourceProtectionProfile, err error) {
	result = &v1alpha1.ClusterResourceProtectionProfile{}
	err = c.client.Patch(pt).
		Resource("clusterresourceprotectionprofiles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
