apiVersion: apps/v1
kind: Deployment
metadata:
  name: ishield-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ishield-sample-app
  template:
    metadata:
      labels:
        app: ishield-sample-app
    spec:
      containers:
      - name: ishield-sample-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: docker.io/pipeline-demo/sample-app:rc1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ishield-sample-service
  labels:
    app: ishield-sample-service
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: ishield-sample-app
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ishield-sampple-app-config
  labels:
    app: ishield-sampple-app-config
data:
  ishield-app.properties: |
    message= This application has been signed.
    
  
