apiVersion: apis.integrityenforcer.io/v1alpha1
kind: IntegrityEnforcer
metadata:
  name: integrity-enforcer-server
spec:
  namespace: integrity-enforcer-ns
  enforcerConfig:
    verifyType: pgp # x509
    monitoringNamespaces:
    - secure-ns
    - test-ns
    - integrity-*
  signPolicy:
    policies:
    - namespaces:
      - "*"
      signers:
      - "SampleSigner"
    signers:
    - name: "SampleSigner"
      secret: keyring-secret
      subjects:
      - email: "hirokuni.kitahara1@ibm.com"
  keyRingConfigs:
  - name: keyring-secret
  server:
    image: integrityenforcer/ie-server:0.0.4dev2
  logger:
    image: integrityenforcer/ie-logging:0.0.4dev2
