apiVersion: apis.integrityenforcer.io/v1alpha1
kind: IntegrityEnforcer
metadata:
  name: integrity-enforcer-server
spec:
  namespace: integrity-enforcer-ns
  enforcerConfig:
    verifyType: pgp # x509
  signPolicy:
    policies:
    - namespaces:
      - "*"
      signers:
      - "SampleSigner"
    signers:
    - name: "SampleSigner"
      secret: keyring-secret
      subjects:
      - email: "sample_signer@signer.com"
  keyRingConfigs:
  - name: keyring-secret
