/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	manifestintegrityprofilev1 "github.com/IBM/integrity-enforcer/webhook/admission-controller/pkg/apis/manifestintegrityprofile/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManifestIntegrityProfiles implements ManifestIntegrityProfileInterface
type FakeManifestIntegrityProfiles struct {
	Fake *FakeApisV1
}

var manifestintegrityprofilesResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1", Resource: "manifestintegrityprofiles"}

var manifestintegrityprofilesKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1", Kind: "ManifestIntegrityProfile"}

// Get takes name of the manifestIntegrityProfile, and returns the corresponding manifestIntegrityProfile object, and an error if there is any.
func (c *FakeManifestIntegrityProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *manifestintegrityprofilev1.ManifestIntegrityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(manifestintegrityprofilesResource, name), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityprofilev1.ManifestIntegrityProfile), err
}

// List takes label and field selectors, and returns the list of ManifestIntegrityProfiles that match those selectors.
func (c *FakeManifestIntegrityProfiles) List(ctx context.Context, opts v1.ListOptions) (result *manifestintegrityprofilev1.ManifestIntegrityProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(manifestintegrityprofilesResource, manifestintegrityprofilesKind, opts), &manifestintegrityprofilev1.ManifestIntegrityProfileList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &manifestintegrityprofilev1.ManifestIntegrityProfileList{ListMeta: obj.(*manifestintegrityprofilev1.ManifestIntegrityProfileList).ListMeta}
	for _, item := range obj.(*manifestintegrityprofilev1.ManifestIntegrityProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityProfiles.
func (c *FakeManifestIntegrityProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(manifestintegrityprofilesResource, opts))
}

// Create takes the representation of a manifestIntegrityProfile and creates it.  Returns the server's representation of the manifestIntegrityProfile, and an error, if there is any.
func (c *FakeManifestIntegrityProfiles) Create(ctx context.Context, manifestIntegrityProfile *manifestintegrityprofilev1.ManifestIntegrityProfile, opts v1.CreateOptions) (result *manifestintegrityprofilev1.ManifestIntegrityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(manifestintegrityprofilesResource, manifestIntegrityProfile), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityprofilev1.ManifestIntegrityProfile), err
}

// Update takes the representation of a manifestIntegrityProfile and updates it. Returns the server's representation of the manifestIntegrityProfile, and an error, if there is any.
func (c *FakeManifestIntegrityProfiles) Update(ctx context.Context, manifestIntegrityProfile *manifestintegrityprofilev1.ManifestIntegrityProfile, opts v1.UpdateOptions) (result *manifestintegrityprofilev1.ManifestIntegrityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(manifestintegrityprofilesResource, manifestIntegrityProfile), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityprofilev1.ManifestIntegrityProfile), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManifestIntegrityProfiles) UpdateStatus(ctx context.Context, manifestIntegrityProfile *manifestintegrityprofilev1.ManifestIntegrityProfile, opts v1.UpdateOptions) (*manifestintegrityprofilev1.ManifestIntegrityProfile, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(manifestintegrityprofilesResource, "status", manifestIntegrityProfile), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityprofilev1.ManifestIntegrityProfile), err
}

// Delete takes name of the manifestIntegrityProfile and deletes it. Returns an error if one occurs.
func (c *FakeManifestIntegrityProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(manifestintegrityprofilesResource, name), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManifestIntegrityProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(manifestintegrityprofilesResource, listOpts)

	_, err := c.Fake.Invokes(action, &manifestintegrityprofilev1.ManifestIntegrityProfileList{})
	return err
}

// Patch applies the patch and returns the patched manifestIntegrityProfile.
func (c *FakeManifestIntegrityProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *manifestintegrityprofilev1.ManifestIntegrityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(manifestintegrityprofilesResource, name, pt, data, subresources...), &manifestintegrityprofilev1.ManifestIntegrityProfile{})
	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityprofilev1.ManifestIntegrityProfile), err
}
