//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/IBM/integrity-enforcer/verifier/pkg/apis/helmreleasemetadata/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHelmReleaseMetadatas implements HelmReleaseMetadataInterface
type FakeHelmReleaseMetadatas struct {
	Fake *FakeIntegrityverifierV1alpha1
	ns   string
}

var helmreleasemetadatasResource = schema.GroupVersionResource{Group: "integrityverifier.io", Version: "v1alpha1", Resource: "helmreleasemetadatas"}

var helmreleasemetadatasKind = schema.GroupVersionKind{Group: "integrityverifier.io", Version: "v1alpha1", Kind: "HelmReleaseMetadata"}

// Get takes name of the helmReleaseMetadata, and returns the corresponding helmReleaseMetadata object, and an error if there is any.
func (c *FakeHelmReleaseMetadatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HelmReleaseMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(helmreleasemetadatasResource, c.ns, name), &v1alpha1.HelmReleaseMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmReleaseMetadata), err
}

// List takes label and field selectors, and returns the list of HelmReleaseMetadatas that match those selectors.
func (c *FakeHelmReleaseMetadatas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HelmReleaseMetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(helmreleasemetadatasResource, helmreleasemetadatasKind, c.ns, opts), &v1alpha1.HelmReleaseMetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HelmReleaseMetadataList{ListMeta: obj.(*v1alpha1.HelmReleaseMetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.HelmReleaseMetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helmReleaseMetadatas.
func (c *FakeHelmReleaseMetadatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(helmreleasemetadatasResource, c.ns, opts))

}

// Create takes the representation of a helmReleaseMetadata and creates it.  Returns the server's representation of the helmReleaseMetadata, and an error, if there is any.
func (c *FakeHelmReleaseMetadatas) Create(ctx context.Context, helmReleaseMetadata *v1alpha1.HelmReleaseMetadata, opts v1.CreateOptions) (result *v1alpha1.HelmReleaseMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(helmreleasemetadatasResource, c.ns, helmReleaseMetadata), &v1alpha1.HelmReleaseMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmReleaseMetadata), err
}

// Update takes the representation of a helmReleaseMetadata and updates it. Returns the server's representation of the helmReleaseMetadata, and an error, if there is any.
func (c *FakeHelmReleaseMetadatas) Update(ctx context.Context, helmReleaseMetadata *v1alpha1.HelmReleaseMetadata, opts v1.UpdateOptions) (result *v1alpha1.HelmReleaseMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(helmreleasemetadatasResource, c.ns, helmReleaseMetadata), &v1alpha1.HelmReleaseMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmReleaseMetadata), err
}

// Delete takes name of the helmReleaseMetadata and deletes it. Returns an error if one occurs.
func (c *FakeHelmReleaseMetadatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(helmreleasemetadatasResource, c.ns, name), &v1alpha1.HelmReleaseMetadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelmReleaseMetadatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(helmreleasemetadatasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HelmReleaseMetadataList{})
	return err
}

// Patch applies the patch and returns the patched helmReleaseMetadata.
func (c *FakeHelmReleaseMetadatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HelmReleaseMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(helmreleasemetadatasResource, c.ns, name, pt, data, subresources...), &v1alpha1.HelmReleaseMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HelmReleaseMetadata), err
}
