//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/enforcerconfig/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/enforcerconfig/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EnforcerConfigsGetter has a method to return a EnforcerConfigInterface.
// A group's client should implement this interface.
type EnforcerConfigsGetter interface {
	EnforcerConfigs(namespace string) EnforcerConfigInterface
}

// EnforcerConfigInterface has methods to work with EnforcerConfig resources.
type EnforcerConfigInterface interface {
	Create(ctx context.Context, enforcerConfig *v1alpha1.EnforcerConfig, opts v1.CreateOptions) (*v1alpha1.EnforcerConfig, error)
	Update(ctx context.Context, enforcerConfig *v1alpha1.EnforcerConfig, opts v1.UpdateOptions) (*v1alpha1.EnforcerConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.EnforcerConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.EnforcerConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EnforcerConfig, err error)
	EnforcerConfigExpansion
}

// enforcerConfigs implements EnforcerConfigInterface
type enforcerConfigs struct {
	client rest.Interface
	ns     string
}

// newEnforcerConfigs returns a EnforcerConfigs
func newEnforcerConfigs(c *ApisV1alpha1Client, namespace string) *enforcerConfigs {
	return &enforcerConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the enforcerConfig, and returns the corresponding enforcerConfig object, and an error if there is any.
func (c *enforcerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EnforcerConfig, err error) {
	result = &v1alpha1.EnforcerConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EnforcerConfigs that match those selectors.
func (c *enforcerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EnforcerConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EnforcerConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested enforcerConfigs.
func (c *enforcerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a enforcerConfig and creates it.  Returns the server's representation of the enforcerConfig, and an error, if there is any.
func (c *enforcerConfigs) Create(ctx context.Context, enforcerConfig *v1alpha1.EnforcerConfig, opts v1.CreateOptions) (result *v1alpha1.EnforcerConfig, err error) {
	result = &v1alpha1.EnforcerConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(enforcerConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a enforcerConfig and updates it. Returns the server's representation of the enforcerConfig, and an error, if there is any.
func (c *enforcerConfigs) Update(ctx context.Context, enforcerConfig *v1alpha1.EnforcerConfig, opts v1.UpdateOptions) (result *v1alpha1.EnforcerConfig, err error) {
	result = &v1alpha1.EnforcerConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		Name(enforcerConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(enforcerConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the enforcerConfig and deletes it. Returns an error if one occurs.
func (c *enforcerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *enforcerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("enforcerconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched enforcerConfig.
func (c *enforcerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EnforcerConfig, err error) {
	result = &v1alpha1.EnforcerConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("enforcerconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
