/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/vresourcesignature/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVResourceSignatures implements VResourceSignatureInterface
type FakeVResourceSignatures struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var vresourcesignaturesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "vresourcesignatures"}

var vresourcesignaturesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "VResourceSignature"}

// Get takes name of the vResourceSignature, and returns the corresponding vResourceSignature object, and an error if there is any.
func (c *FakeVResourceSignatures) Get(name string, options v1.GetOptions) (result *v1alpha1.VResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vresourcesignaturesResource, c.ns, name), &v1alpha1.VResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceSignature), err
}

// List takes label and field selectors, and returns the list of VResourceSignatures that match those selectors.
func (c *FakeVResourceSignatures) List(opts v1.ListOptions) (result *v1alpha1.VResourceSignatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vresourcesignaturesResource, vresourcesignaturesKind, c.ns, opts), &v1alpha1.VResourceSignatureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VResourceSignatureList{ListMeta: obj.(*v1alpha1.VResourceSignatureList).ListMeta}
	for _, item := range obj.(*v1alpha1.VResourceSignatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vResourceSignatures.
func (c *FakeVResourceSignatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vresourcesignaturesResource, c.ns, opts))

}

// Create takes the representation of a vResourceSignature and creates it.  Returns the server's representation of the vResourceSignature, and an error, if there is any.
func (c *FakeVResourceSignatures) Create(vResourceSignature *v1alpha1.VResourceSignature) (result *v1alpha1.VResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vresourcesignaturesResource, c.ns, vResourceSignature), &v1alpha1.VResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceSignature), err
}

// Update takes the representation of a vResourceSignature and updates it. Returns the server's representation of the vResourceSignature, and an error, if there is any.
func (c *FakeVResourceSignatures) Update(vResourceSignature *v1alpha1.VResourceSignature) (result *v1alpha1.VResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vresourcesignaturesResource, c.ns, vResourceSignature), &v1alpha1.VResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceSignature), err
}

// Delete takes name of the vResourceSignature and deletes it. Returns an error if one occurs.
func (c *FakeVResourceSignatures) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vresourcesignaturesResource, c.ns, name), &v1alpha1.VResourceSignature{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVResourceSignatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vresourcesignaturesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VResourceSignatureList{})
	return err
}

// Patch applies the patch and returns the patched vResourceSignature.
func (c *FakeVResourceSignatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vresourcesignaturesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VResourceSignature), err
}
