//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/enforcepolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnforcePolicies implements EnforcePolicyInterface
type FakeEnforcePolicies struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var enforcepoliciesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "enforcepolicies"}

var enforcepoliciesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "EnforcePolicy"}

// Get takes name of the enforcePolicy, and returns the corresponding enforcePolicy object, and an error if there is any.
func (c *FakeEnforcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.EnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(enforcepoliciesResource, c.ns, name), &v1alpha1.EnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnforcePolicy), err
}

// List takes label and field selectors, and returns the list of EnforcePolicies that match those selectors.
func (c *FakeEnforcePolicies) List(opts v1.ListOptions) (result *v1alpha1.EnforcePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(enforcepoliciesResource, enforcepoliciesKind, c.ns, opts), &v1alpha1.EnforcePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EnforcePolicyList{ListMeta: obj.(*v1alpha1.EnforcePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.EnforcePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested enforcePolicies.
func (c *FakeEnforcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(enforcepoliciesResource, c.ns, opts))

}

// Create takes the representation of a enforcePolicy and creates it.  Returns the server's representation of the enforcePolicy, and an error, if there is any.
func (c *FakeEnforcePolicies) Create(enforcePolicy *v1alpha1.EnforcePolicy) (result *v1alpha1.EnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(enforcepoliciesResource, c.ns, enforcePolicy), &v1alpha1.EnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnforcePolicy), err
}

// Update takes the representation of a enforcePolicy and updates it. Returns the server's representation of the enforcePolicy, and an error, if there is any.
func (c *FakeEnforcePolicies) Update(enforcePolicy *v1alpha1.EnforcePolicy) (result *v1alpha1.EnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(enforcepoliciesResource, c.ns, enforcePolicy), &v1alpha1.EnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnforcePolicy), err
}

// Delete takes name of the enforcePolicy and deletes it. Returns an error if one occurs.
func (c *FakeEnforcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(enforcepoliciesResource, c.ns, name), &v1alpha1.EnforcePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnforcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(enforcepoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnforcePolicyList{})
	return err
}

// Patch applies the patch and returns the patched enforcePolicy.
func (c *FakeEnforcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnforcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(enforcepoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EnforcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnforcePolicy), err
}
