/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/iesignerpolicy/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/iesignerpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IESignerPoliciesGetter has a method to return a IESignerPolicyInterface.
// A group's client should implement this interface.
type IESignerPoliciesGetter interface {
	IESignerPolicies(namespace string) IESignerPolicyInterface
}

// IESignerPolicyInterface has methods to work with IESignerPolicy resources.
type IESignerPolicyInterface interface {
	Create(*v1alpha1.IESignerPolicy) (*v1alpha1.IESignerPolicy, error)
	Update(*v1alpha1.IESignerPolicy) (*v1alpha1.IESignerPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IESignerPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.IESignerPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IESignerPolicy, err error)
	IESignerPolicyExpansion
}

// iESignerPolicies implements IESignerPolicyInterface
type iESignerPolicies struct {
	client rest.Interface
	ns     string
}

// newIESignerPolicies returns a IESignerPolicies
func newIESignerPolicies(c *ResearchV1alpha1Client, namespace string) *iESignerPolicies {
	return &iESignerPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iESignerPolicy, and returns the corresponding iESignerPolicy object, and an error if there is any.
func (c *iESignerPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.IESignerPolicy, err error) {
	result = &v1alpha1.IESignerPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IESignerPolicies that match those selectors.
func (c *iESignerPolicies) List(opts v1.ListOptions) (result *v1alpha1.IESignerPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IESignerPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iESignerPolicies.
func (c *iESignerPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iESignerPolicy and creates it.  Returns the server's representation of the iESignerPolicy, and an error, if there is any.
func (c *iESignerPolicies) Create(iESignerPolicy *v1alpha1.IESignerPolicy) (result *v1alpha1.IESignerPolicy, err error) {
	result = &v1alpha1.IESignerPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		Body(iESignerPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iESignerPolicy and updates it. Returns the server's representation of the iESignerPolicy, and an error, if there is any.
func (c *iESignerPolicies) Update(iESignerPolicy *v1alpha1.IESignerPolicy) (result *v1alpha1.IESignerPolicy, err error) {
	result = &v1alpha1.IESignerPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		Name(iESignerPolicy.Name).
		Body(iESignerPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the iESignerPolicy and deletes it. Returns an error if one occurs.
func (c *iESignerPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iESignerPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iesignerpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iESignerPolicy.
func (c *iESignerPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IESignerPolicy, err error) {
	result = &v1alpha1.IESignerPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("iesignerpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
