/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/appenforcepolicy/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/appenforcepolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppEnforcePoliciesGetter has a method to return a AppEnforcePolicyInterface.
// A group's client should implement this interface.
type AppEnforcePoliciesGetter interface {
	AppEnforcePolicies(namespace string) AppEnforcePolicyInterface
}

// AppEnforcePolicyInterface has methods to work with AppEnforcePolicy resources.
type AppEnforcePolicyInterface interface {
	Create(*v1alpha1.AppEnforcePolicy) (*v1alpha1.AppEnforcePolicy, error)
	Update(*v1alpha1.AppEnforcePolicy) (*v1alpha1.AppEnforcePolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AppEnforcePolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.AppEnforcePolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppEnforcePolicy, err error)
	AppEnforcePolicyExpansion
}

// appEnforcePolicies implements AppEnforcePolicyInterface
type appEnforcePolicies struct {
	client rest.Interface
	ns     string
}

// newAppEnforcePolicies returns a AppEnforcePolicies
func newAppEnforcePolicies(c *ResearchV1alpha1Client, namespace string) *appEnforcePolicies {
	return &appEnforcePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the appEnforcePolicy, and returns the corresponding appEnforcePolicy object, and an error if there is any.
func (c *appEnforcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.AppEnforcePolicy, err error) {
	result = &v1alpha1.AppEnforcePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppEnforcePolicies that match those selectors.
func (c *appEnforcePolicies) List(opts v1.ListOptions) (result *v1alpha1.AppEnforcePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AppEnforcePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appEnforcePolicies.
func (c *appEnforcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a appEnforcePolicy and creates it.  Returns the server's representation of the appEnforcePolicy, and an error, if there is any.
func (c *appEnforcePolicies) Create(appEnforcePolicy *v1alpha1.AppEnforcePolicy) (result *v1alpha1.AppEnforcePolicy, err error) {
	result = &v1alpha1.AppEnforcePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		Body(appEnforcePolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a appEnforcePolicy and updates it. Returns the server's representation of the appEnforcePolicy, and an error, if there is any.
func (c *appEnforcePolicies) Update(appEnforcePolicy *v1alpha1.AppEnforcePolicy) (result *v1alpha1.AppEnforcePolicy, err error) {
	result = &v1alpha1.AppEnforcePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		Name(appEnforcePolicy.Name).
		Body(appEnforcePolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the appEnforcePolicy and deletes it. Returns an error if one occurs.
func (c *appEnforcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appEnforcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("appenforcepolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched appEnforcePolicy.
func (c *appEnforcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppEnforcePolicy, err error) {
	result = &v1alpha1.AppEnforcePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("appenforcepolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
