apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apis.integrityverifier.io/v1alpha1",
          "kind": "IntegrityVerifier",
          "metadata": {
            "name": "integrity-verifier-server"
          },
          "spec": {
            "keyRingConfigs": [
              {
                "name": "keyring-secret"
              }
            ],
            "namespace": "integrity-verifier-operator-system",
            "signPolicy": {
              "policies": [
                {
                  "namespaces": [
                    "*"
                  ],
                  "signers": [
                    "SampleSigner"
                  ]
                },
                {
                  "scope": "Cluster",
                  "signers": [
                    "SampleSigner"
                  ]
                }
              ],
              "signers": [
                {
                  "name": "SampleSigner",
                  "secret": "keyring-secret",
                  "subjects": [
                    {
                      "email": "sample_signer@signer.com"
                    }
                  ]
                }
              ]
            },
            "verifierConfig": {
              "inScopeNamespaceSelector": {
                "exclude": [
                  "kube-*",
                  "openshift-*"
                ],
                "include": [
                  "*"
                ]
              },
              "verifyType": "pgp"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: integrity-verifier-operator.v0.0.4
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: IntegrityVerifier is the Schema for the integrityverifiers API
        displayName: Integrity Verifier
        kind: IntegrityVerifier
        name: integrityverifiers.apis.integrityverifier.io
        version: v1alpha1
  description: Integrity Verifier Operator
  displayName: Integrity Verifier Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - '*'
            - apiGroups:
                - apis.integrityverifier.io
              resources:
                - helmreleasemetadatas
                - integrityverifiers
                - integrityverifiers/finalizers
                - resourcesignatures
                - resourcesigningprofiles
                - signpolicies
                - verifierconfigs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - daemonsets
                - deployments
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
                - replicasets
              verbs:
                - get
            - apiGroups:
                - apps
              resourceNames:
                - integrity-verifier-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ""
              resources:
                - configmaps
                - endpoints
                - events
                - persistentvolumeclaims
                - pods
                - secrets
                - serviceaccounts
                - services
                - services/finalizers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - create
                - get
            - apiGroups:
                - policy
              resources:
                - podsecuritypolicies
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
                - rolebindings
                - roles
              verbs:
                - '*'
            - apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              verbs:
                - '*'
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: integrity-verifier-operator-manager
      deployments:
        - name: integrity-verifier-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=10
                    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                    resources: {}
                  - args:
                      - --metrics-addr=127.0.0.1:8080
                      - --enable-leader-election
                    command:
                      - /iv-op-app/manager
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    image: integrityverifier/integrity-verifier-operator:0.0.4
                    imagePullPolicy: Always
                    name: manager
                    resources:
                      limits:
                        cpu: 500m
                        memory: 500Mi
                      requests:
                        cpu: 200m
                        memory: 200Mi
                imagePullSecrets:
                  - name: mappregkey
                serviceAccountName: integrity-verifier-operator-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - get
                - update
                - patch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: integrity-verifier-operator-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - integrity
  links:
    - name: Integrity Verifier Operator
      url: https://integrity-verifier-operator.domain
  maturity: alpha
  provider:
    name: IBM
    url: https://github.com/ibm/integrity-enforcer
  version: 0.0.4
