apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: integrity-shield-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IntegrityShield is the Schema for the integrityshields API
      displayName: Integrity Shield
      kind: IntegrityShield
      name: integrityshields.apis.integrityshield.io
      version: v1alpha1
  description: Integrity Shield Operator
  displayName: Integrity Shield Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - integrity
  links:
  - name: Integrity Shield Operator
    url: https://integrity-shield-operator.domain
  maturity: alpha
  provider:
    name: IBM
    url: https://github.com/ibm/integrity-enforcer
  version: 0.0.0
