apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ie-admin-role
  namespace: integrity-enforcer-ns
rules:
  - apiGroups:
    - ""
    resources:
    - integrityenforcers
    - enforcerconfigs
    - signpolicies
    verbs:
    - create
    - delete
    - update
    - get
    - list
    - watch
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ie-admin-cluster-role
rules:
  - apiGroups:
    - ""
    resources:
    - resourceprotectionprofiles
    - resourcesignatures
    - clusterresourceprotectionprofiles
    verbs:
    - create
    - delete
    - update
    - get
    - list
    - watch
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ie-admin-rolebinding
    namespace: integrity-enforcer-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ie-admin-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ie-admin-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ie-admin-cluster-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters