apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iv-admin-role
  namespace: integrity-verifier-operator-system
rules:
  - apiGroups:
    - ""
    resources:
    - integrityverifiers
    - verifierconfigs
    - signpolicies
    verbs:
    - create
    - delete
    - update
    - get
    - list
    - watch
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iv-admin-cluster-role
rules:
  - apiGroups:
    - ""
    resources:
    - resourcesigningprofiles
    - resourcesignatures
    verbs:
    - create
    - delete
    - update
    - get
    - list
    - watch
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: iv-admin-rolebinding
    namespace: integrity-verifier-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iv-admin-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: iv-admin-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iv-admin-cluster-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters