apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apis.integrityshield.io/v1alpha1",
          "kind": "IntegrityShield",
          "metadata": {
            "name": "integrity-shield-server"
          },
          "spec": {
            "keyConfig": [
              {
                "name": "sample-signer-keyconfig",
                "secretName": "keyring-secret"
              }
            ],
            "namespace": "integrity-shield-operator-system",
            "shieldConfig": {
              "inScopeNamespaceSelector": {
                "exclude": [
                  "kube-*",
                  "openshift-*"
                ],
                "include": [
                  "*"
                ]
              }
            },
            "signerConfig": {
              "policies": [
                {
                  "namespaces": [
                    "*"
                  ],
                  "signers": [
                    "SampleSigner"
                  ]
                },
                {
                  "scope": "Cluster",
                  "signers": [
                    "SampleSigner"
                  ]
                }
              ],
              "signers": [
                {
                  "keyConfig": "sample-signer-keyconfig",
                  "name": "SampleSigner",
                  "subjects": [
                    {
                      "email": "*"
                    }
                  ]
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: "Security"
    createdAt: 2021-01-13T18:00:00Z
    certified: 'false'
    containerImage: https://quay.io/repository/open-cluster-management/integrity-shield-operator
    repository: https://github.com/open-cluster-management/integrity-shield
    support: Community
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: integrity-shield-operator.v0.1.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: IntegrityShield is the Schema for the integrityshields API
        displayName: Integrity Shield
        kind: IntegrityShield
        name: integrityshields.apis.integrityshield.io
        version: v1alpha1
  description: Integrity Shield Operator
  displayName: Integrity Shield Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - '*'
            - apiGroups:
                - apis.integrityshield.io
              resources:
                - helmreleasemetadatas
                - integrityshields
                - integrityshields/finalizers
                - resourcesignatures
                - resourcesigningprofiles
                - shieldconfigs
                - signerconfigs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - configmaps
                - events
                - secrets
                - serviceaccounts
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - podsecuritypolicies
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
                - rolebindings
                - roles
              verbs:
                - '*'
          serviceAccountName: integrity-shield-operator-manager
      deployments:
        - name: integrity-shield-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --enable-leader-election
                    command:
                      - /ishield-op-app/manager
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    image: quay.io/open-cluster-management/integrity-shield-operator:0.1.3
                    imagePullPolicy: Always
                    name: manager
                    resources:
                      limits:
                        cpu: 500m
                        memory: 500Mi
                      requests:
                        cpu: 200m
                        memory: 200Mi
                imagePullSecrets:
                  - name: mappregkey
                serviceAccountName: integrity-shield-operator-manager
                terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - integrity
  links:
    - name: K8s Integrity Shield Operator
      url: https://github.com/open-cluster-management/integrity-shield
    - name: Operator Documentation
      url: https://github.com/open-cluster-management/integrity-shield/tree/master/docs
  maintainers:
  - email:  acm-contact@redhat.com
    name: Community
  maturity: alpha
  provider:
    name: Community
    url: https://github.com/open-cluster-management/integrity-shield
  version: 0.1.3
