apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: integrity-shield-operator-manager
      imagePullSecrets:
      - name: mappregkey
      containers:
      - command:
        - /ishield-op-app/manager
        args:
        - --enable-leader-election
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        livenessProbe:
          exec:
            command: ["ls"]
        readinessProbe:
          exec:
            command: ["ls"]
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - "curl -sk -X PATCH https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/apis/apis.integrityshield.io/v1alpha1/namespaces/$POD_NAMESPACE/integrityshields/integrity-shield-server -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" -H \"Content-Type: application/merge-patch+json\" -d '{\"metadata\":{\"finalizers\":[\"cleanup.finalizers.integrityshield.io\"]}}'"
          preStop:
            exec:
              command:
              - bash
              - -c
              - "curl -sk -X DELETE https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/ishield-webhook-config -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" && curl -sk -X PATCH https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/apis/apis.integrityshield.io/v1alpha1/namespaces/$POD_NAMESPACE/integrityshields/integrity-shield-server -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" -H \"Content-Type: application/merge-patch+json\" -d '{\"metadata\":{\"finalizers\":[]}}'"

        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
