//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/resourcesignature/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceSignatures implements ResourceSignatureInterface
type FakeResourceSignatures struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var resourcesignaturesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "resourcesignatures"}

var resourcesignaturesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "ResourceSignature"}

// Get takes name of the resourceSignature, and returns the corresponding resourceSignature object, and an error if there is any.
func (c *FakeResourceSignatures) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcesignaturesResource, c.ns, name), &v1alpha1.ResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceSignature), err
}

// List takes label and field selectors, and returns the list of ResourceSignatures that match those selectors.
func (c *FakeResourceSignatures) List(opts v1.ListOptions) (result *v1alpha1.ResourceSignatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcesignaturesResource, resourcesignaturesKind, c.ns, opts), &v1alpha1.ResourceSignatureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceSignatureList{ListMeta: obj.(*v1alpha1.ResourceSignatureList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceSignatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceSignatures.
func (c *FakeResourceSignatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcesignaturesResource, c.ns, opts))

}

// Create takes the representation of a resourceSignature and creates it.  Returns the server's representation of the resourceSignature, and an error, if there is any.
func (c *FakeResourceSignatures) Create(resourceSignature *v1alpha1.ResourceSignature) (result *v1alpha1.ResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcesignaturesResource, c.ns, resourceSignature), &v1alpha1.ResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceSignature), err
}

// Update takes the representation of a resourceSignature and updates it. Returns the server's representation of the resourceSignature, and an error, if there is any.
func (c *FakeResourceSignatures) Update(resourceSignature *v1alpha1.ResourceSignature) (result *v1alpha1.ResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcesignaturesResource, c.ns, resourceSignature), &v1alpha1.ResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceSignature), err
}

// Delete takes name of the resourceSignature and deletes it. Returns an error if one occurs.
func (c *FakeResourceSignatures) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourcesignaturesResource, c.ns, name), &v1alpha1.ResourceSignature{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceSignatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcesignaturesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceSignatureList{})
	return err
}

// Patch applies the patch and returns the patched resourceSignature.
func (c *FakeResourceSignatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceSignature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcesignaturesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceSignature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceSignature), err
}
