nameReference:
- kind: ServiceAccount
  version: v1
  fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/serviceAccountName
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/volumes/secret/secretName
  

namespace:
- kind: Namespace
  version: v1
  path: metadata/namespace
  create: true