apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrity-enforcer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: integrity-enforcer-operator
  template:
    metadata:
      labels:
        name: integrity-enforcer-operator
    spec:
      serviceAccountName: integrity-enforcer-operator
      # imagePullSecrets:
      #   - name: CHANGEME
      containers:          
        - name: integrity-enforcer-operator
          # Replace this with the built image name
          image: 'integrityenforcer/integrity-enforcer-operator:0.0.3rc2'
          command:
          - integrity-enforcer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "integrity-enforcer-operator"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
