/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	manifestintegritystatev1 "github.com/stolostron/integrity-shield/observer/pkg/apis/manifestintegritystate/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManifestIntegrityStates implements ManifestIntegrityStateInterface
type FakeManifestIntegrityStates struct {
	Fake *FakeApisV1
	ns   string
}

var manifestintegritystatesResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1", Resource: "manifestintegritystates"}

var manifestintegritystatesKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1", Kind: "ManifestIntegrityState"}

// Get takes name of the manifestIntegrityState, and returns the corresponding manifestIntegrityState object, and an error if there is any.
func (c *FakeManifestIntegrityStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *manifestintegritystatev1.ManifestIntegrityState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manifestintegritystatesResource, c.ns, name), &manifestintegritystatev1.ManifestIntegrityState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritystatev1.ManifestIntegrityState), err
}

// List takes label and field selectors, and returns the list of ManifestIntegrityStates that match those selectors.
func (c *FakeManifestIntegrityStates) List(ctx context.Context, opts v1.ListOptions) (result *manifestintegritystatev1.ManifestIntegrityStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manifestintegritystatesResource, manifestintegritystatesKind, c.ns, opts), &manifestintegritystatev1.ManifestIntegrityStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &manifestintegritystatev1.ManifestIntegrityStateList{ListMeta: obj.(*manifestintegritystatev1.ManifestIntegrityStateList).ListMeta}
	for _, item := range obj.(*manifestintegritystatev1.ManifestIntegrityStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityStates.
func (c *FakeManifestIntegrityStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manifestintegritystatesResource, c.ns, opts))

}

// Create takes the representation of a manifestIntegrityState and creates it.  Returns the server's representation of the manifestIntegrityState, and an error, if there is any.
func (c *FakeManifestIntegrityStates) Create(ctx context.Context, manifestIntegrityState *manifestintegritystatev1.ManifestIntegrityState, opts v1.CreateOptions) (result *manifestintegritystatev1.ManifestIntegrityState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manifestintegritystatesResource, c.ns, manifestIntegrityState), &manifestintegritystatev1.ManifestIntegrityState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritystatev1.ManifestIntegrityState), err
}

// Update takes the representation of a manifestIntegrityState and updates it. Returns the server's representation of the manifestIntegrityState, and an error, if there is any.
func (c *FakeManifestIntegrityStates) Update(ctx context.Context, manifestIntegrityState *manifestintegritystatev1.ManifestIntegrityState, opts v1.UpdateOptions) (result *manifestintegritystatev1.ManifestIntegrityState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manifestintegritystatesResource, c.ns, manifestIntegrityState), &manifestintegritystatev1.ManifestIntegrityState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritystatev1.ManifestIntegrityState), err
}

// Delete takes name of the manifestIntegrityState and deletes it. Returns an error if one occurs.
func (c *FakeManifestIntegrityStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manifestintegritystatesResource, c.ns, name), &manifestintegritystatev1.ManifestIntegrityState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManifestIntegrityStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manifestintegritystatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &manifestintegritystatev1.ManifestIntegrityStateList{})
	return err
}

// Patch applies the patch and returns the patched manifestIntegrityState.
func (c *FakeManifestIntegrityStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *manifestintegritystatev1.ManifestIntegrityState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manifestintegritystatesResource, c.ns, name, pt, data, subresources...), &manifestintegritystatev1.ManifestIntegrityState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritystatev1.ManifestIntegrityState), err
}
