//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/resourceprotectionprofile/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceProtectionProfiles implements ResourceProtectionProfileInterface
type FakeResourceProtectionProfiles struct {
	Fake *FakeResearchV1alpha1
	ns   string
}

var resourceprotectionprofilesResource = schema.GroupVersionResource{Group: "research.ibm.com", Version: "v1alpha1", Resource: "resourceprotectionprofiles"}

var resourceprotectionprofilesKind = schema.GroupVersionKind{Group: "research.ibm.com", Version: "v1alpha1", Kind: "ResourceProtectionProfile"}

// Get takes name of the resourceProtectionProfile, and returns the corresponding resourceProtectionProfile object, and an error if there is any.
func (c *FakeResourceProtectionProfiles) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourceprotectionprofilesResource, c.ns, name), &v1alpha1.ResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceProtectionProfile), err
}

// List takes label and field selectors, and returns the list of ResourceProtectionProfiles that match those selectors.
func (c *FakeResourceProtectionProfiles) List(opts v1.ListOptions) (result *v1alpha1.ResourceProtectionProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourceprotectionprofilesResource, resourceprotectionprofilesKind, c.ns, opts), &v1alpha1.ResourceProtectionProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceProtectionProfileList{ListMeta: obj.(*v1alpha1.ResourceProtectionProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceProtectionProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceProtectionProfiles.
func (c *FakeResourceProtectionProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourceprotectionprofilesResource, c.ns, opts))

}

// Create takes the representation of a resourceProtectionProfile and creates it.  Returns the server's representation of the resourceProtectionProfile, and an error, if there is any.
func (c *FakeResourceProtectionProfiles) Create(resourceProtectionProfile *v1alpha1.ResourceProtectionProfile) (result *v1alpha1.ResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourceprotectionprofilesResource, c.ns, resourceProtectionProfile), &v1alpha1.ResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceProtectionProfile), err
}

// Update takes the representation of a resourceProtectionProfile and updates it. Returns the server's representation of the resourceProtectionProfile, and an error, if there is any.
func (c *FakeResourceProtectionProfiles) Update(resourceProtectionProfile *v1alpha1.ResourceProtectionProfile) (result *v1alpha1.ResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourceprotectionprofilesResource, c.ns, resourceProtectionProfile), &v1alpha1.ResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceProtectionProfile), err
}

// Delete takes name of the resourceProtectionProfile and deletes it. Returns an error if one occurs.
func (c *FakeResourceProtectionProfiles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourceprotectionprofilesResource, c.ns, name), &v1alpha1.ResourceProtectionProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceProtectionProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourceprotectionprofilesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceProtectionProfileList{})
	return err
}

// Patch applies the patch and returns the patched resourceProtectionProfile.
func (c *FakeResourceProtectionProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceProtectionProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourceprotectionprofilesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceProtectionProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceProtectionProfile), err
}
