/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	manifestintegritydecisionv1 "github.com/stolostron/integrity-shield/reporter/pkg/apis/manifestintegritydecision/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManifestIntegrityDecisions implements ManifestIntegrityDecisionInterface
type FakeManifestIntegrityDecisions struct {
	Fake *FakeApisV1
	ns   string
}

var manifestintegritydecisionsResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1", Resource: "manifestintegritydecisions"}

var manifestintegritydecisionsKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1", Kind: "ManifestIntegrityDecision"}

// Get takes name of the manifestIntegrityDecision, and returns the corresponding manifestIntegrityDecision object, and an error if there is any.
func (c *FakeManifestIntegrityDecisions) Get(ctx context.Context, name string, options v1.GetOptions) (result *manifestintegritydecisionv1.ManifestIntegrityDecision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manifestintegritydecisionsResource, c.ns, name), &manifestintegritydecisionv1.ManifestIntegrityDecision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritydecisionv1.ManifestIntegrityDecision), err
}

// List takes label and field selectors, and returns the list of ManifestIntegrityDecisions that match those selectors.
func (c *FakeManifestIntegrityDecisions) List(ctx context.Context, opts v1.ListOptions) (result *manifestintegritydecisionv1.ManifestIntegrityDecisionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manifestintegritydecisionsResource, manifestintegritydecisionsKind, c.ns, opts), &manifestintegritydecisionv1.ManifestIntegrityDecisionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &manifestintegritydecisionv1.ManifestIntegrityDecisionList{ListMeta: obj.(*manifestintegritydecisionv1.ManifestIntegrityDecisionList).ListMeta}
	for _, item := range obj.(*manifestintegritydecisionv1.ManifestIntegrityDecisionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityDecisions.
func (c *FakeManifestIntegrityDecisions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manifestintegritydecisionsResource, c.ns, opts))

}

// Create takes the representation of a manifestIntegrityDecision and creates it.  Returns the server's representation of the manifestIntegrityDecision, and an error, if there is any.
func (c *FakeManifestIntegrityDecisions) Create(ctx context.Context, manifestIntegrityDecision *manifestintegritydecisionv1.ManifestIntegrityDecision, opts v1.CreateOptions) (result *manifestintegritydecisionv1.ManifestIntegrityDecision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manifestintegritydecisionsResource, c.ns, manifestIntegrityDecision), &manifestintegritydecisionv1.ManifestIntegrityDecision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritydecisionv1.ManifestIntegrityDecision), err
}

// Update takes the representation of a manifestIntegrityDecision and updates it. Returns the server's representation of the manifestIntegrityDecision, and an error, if there is any.
func (c *FakeManifestIntegrityDecisions) Update(ctx context.Context, manifestIntegrityDecision *manifestintegritydecisionv1.ManifestIntegrityDecision, opts v1.UpdateOptions) (result *manifestintegritydecisionv1.ManifestIntegrityDecision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manifestintegritydecisionsResource, c.ns, manifestIntegrityDecision), &manifestintegritydecisionv1.ManifestIntegrityDecision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritydecisionv1.ManifestIntegrityDecision), err
}

// Delete takes name of the manifestIntegrityDecision and deletes it. Returns an error if one occurs.
func (c *FakeManifestIntegrityDecisions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manifestintegritydecisionsResource, c.ns, name), &manifestintegritydecisionv1.ManifestIntegrityDecision{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManifestIntegrityDecisions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manifestintegritydecisionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &manifestintegritydecisionv1.ManifestIntegrityDecisionList{})
	return err
}

// Patch applies the patch and returns the patched manifestIntegrityDecision.
func (c *FakeManifestIntegrityDecisions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *manifestintegritydecisionv1.ManifestIntegrityDecision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manifestintegritydecisionsResource, c.ns, name, pt, data, subresources...), &manifestintegritydecisionv1.ManifestIntegrityDecision{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegritydecisionv1.ManifestIntegrityDecision), err
}
