//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/vresourcesignature/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/vresourcesignature/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VResourceSignaturesGetter has a method to return a VResourceSignatureInterface.
// A group's client should implement this interface.
type VResourceSignaturesGetter interface {
	VResourceSignatures(namespace string) VResourceSignatureInterface
}

// VResourceSignatureInterface has methods to work with VResourceSignature resources.
type VResourceSignatureInterface interface {
	Create(*v1alpha1.VResourceSignature) (*v1alpha1.VResourceSignature, error)
	Update(*v1alpha1.VResourceSignature) (*v1alpha1.VResourceSignature, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VResourceSignature, error)
	List(opts v1.ListOptions) (*v1alpha1.VResourceSignatureList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceSignature, err error)
	VResourceSignatureExpansion
}

// vResourceSignatures implements VResourceSignatureInterface
type vResourceSignatures struct {
	client rest.Interface
	ns     string
}

// newVResourceSignatures returns a VResourceSignatures
func newVResourceSignatures(c *ResearchV1alpha1Client, namespace string) *vResourceSignatures {
	return &vResourceSignatures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vResourceSignature, and returns the corresponding vResourceSignature object, and an error if there is any.
func (c *vResourceSignatures) Get(name string, options v1.GetOptions) (result *v1alpha1.VResourceSignature, err error) {
	result = &v1alpha1.VResourceSignature{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VResourceSignatures that match those selectors.
func (c *vResourceSignatures) List(opts v1.ListOptions) (result *v1alpha1.VResourceSignatureList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VResourceSignatureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vResourceSignatures.
func (c *vResourceSignatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vResourceSignature and creates it.  Returns the server's representation of the vResourceSignature, and an error, if there is any.
func (c *vResourceSignatures) Create(vResourceSignature *v1alpha1.VResourceSignature) (result *v1alpha1.VResourceSignature, err error) {
	result = &v1alpha1.VResourceSignature{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		Body(vResourceSignature).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vResourceSignature and updates it. Returns the server's representation of the vResourceSignature, and an error, if there is any.
func (c *vResourceSignatures) Update(vResourceSignature *v1alpha1.VResourceSignature) (result *v1alpha1.VResourceSignature, err error) {
	result = &v1alpha1.VResourceSignature{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		Name(vResourceSignature.Name).
		Body(vResourceSignature).
		Do().
		Into(result)
	return
}

// Delete takes name of the vResourceSignature and deletes it. Returns an error if one occurs.
func (c *vResourceSignatures) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vResourceSignatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vresourcesignatures").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vResourceSignature.
func (c *vResourceSignatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VResourceSignature, err error) {
	result = &v1alpha1.VResourceSignature{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vresourcesignatures").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
