//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/IBM/integrity-enforcer/shield/pkg/apis/signerconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSignerConfigs implements SignerConfigInterface
type FakeSignerConfigs struct {
	Fake *FakeApisV1alpha1
	ns   string
}

var signerconfigsResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1alpha1", Resource: "signerconfigs"}

var signerconfigsKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1alpha1", Kind: "SignerConfig"}

// Get takes name of the signerConfig, and returns the corresponding signerConfig object, and an error if there is any.
func (c *FakeSignerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SignerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(signerconfigsResource, c.ns, name), &v1alpha1.SignerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignerConfig), err
}

// List takes label and field selectors, and returns the list of SignerConfigs that match those selectors.
func (c *FakeSignerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SignerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(signerconfigsResource, signerconfigsKind, c.ns, opts), &v1alpha1.SignerConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SignerConfigList{ListMeta: obj.(*v1alpha1.SignerConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.SignerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested signerConfigs.
func (c *FakeSignerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(signerconfigsResource, c.ns, opts))

}

// Create takes the representation of a signerConfig and creates it.  Returns the server's representation of the signerConfig, and an error, if there is any.
func (c *FakeSignerConfigs) Create(ctx context.Context, signerConfig *v1alpha1.SignerConfig, opts v1.CreateOptions) (result *v1alpha1.SignerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(signerconfigsResource, c.ns, signerConfig), &v1alpha1.SignerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignerConfig), err
}

// Update takes the representation of a signerConfig and updates it. Returns the server's representation of the signerConfig, and an error, if there is any.
func (c *FakeSignerConfigs) Update(ctx context.Context, signerConfig *v1alpha1.SignerConfig, opts v1.UpdateOptions) (result *v1alpha1.SignerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(signerconfigsResource, c.ns, signerConfig), &v1alpha1.SignerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignerConfig), err
}

// Delete takes name of the signerConfig and deletes it. Returns an error if one occurs.
func (c *FakeSignerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(signerconfigsResource, c.ns, name), &v1alpha1.SignerConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSignerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(signerconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SignerConfigList{})
	return err
}

// Patch applies the patch and returns the patched signerConfig.
func (c *FakeSignerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SignerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(signerconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SignerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SignerConfig), err
}
