apiVersion: research.ibm.com/v1alpha1
kind: SignService
metadata:
  name: signservice
spec:
  enabled: true
  keyRingSecretName: keyring-secret
  privateKeyRingSecretName: private-keyring-secret
  signServiceSecretName: signservice-secret
  ieCertPoolSecretName: ie-certpool-secret
  serviceAccountName: signservice-sa
  imagePullSecrets: []
  certSigners:
  - name: "RootCA"
    isCA: true
  - name: "AdminCA"
    issuerName: "RootCA"
    isCA: true
  - name: "ServiceCert"
    issuerName: "AdminCA"
    isCA: false
  signers:
  - cluster_signer@signer.com
  invalidSigners:
  - invalid_signer@invalid.signer.com
  signService:
    image: integrityenforcer/ie-signservice:0.0.1
    imagePullPolicy: Always
    port: 8180
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    appName: signservice
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000580000

