// +build !ignore_autogenerated

//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedResourceIntegrity) DeepCopyInto(out *ProtectedResourceIntegrity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedResourceIntegrity.
func (in *ProtectedResourceIntegrity) DeepCopy() *ProtectedResourceIntegrity {
	if in == nil {
		return nil
	}
	out := new(ProtectedResourceIntegrity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedResourceIntegrity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedResourceIntegrityList) DeepCopyInto(out *ProtectedResourceIntegrityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProtectedResourceIntegrity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedResourceIntegrityList.
func (in *ProtectedResourceIntegrityList) DeepCopy() *ProtectedResourceIntegrityList {
	if in == nil {
		return nil
	}
	out := new(ProtectedResourceIntegrityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedResourceIntegrityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedResourceIntegritySpec) DeepCopyInto(out *ProtectedResourceIntegritySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedResourceIntegritySpec.
func (in *ProtectedResourceIntegritySpec) DeepCopy() *ProtectedResourceIntegritySpec {
	if in == nil {
		return nil
	}
	out := new(ProtectedResourceIntegritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedResourceIntegrityStatus) DeepCopyInto(out *ProtectedResourceIntegrityStatus) {
	*out = *in
	in.LastVerified.DeepCopyInto(&out.LastVerified)
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedResourceIntegrityStatus.
func (in *ProtectedResourceIntegrityStatus) DeepCopy() *ProtectedResourceIntegrityStatus {
	if in == nil {
		return nil
	}
	out := new(ProtectedResourceIntegrityStatus)
	in.DeepCopyInto(out)
	return out
}
