apiVersion: apis.integrityverifier.io/v1alpha1
kind: IntegrityVerifier
metadata:
  name: integrity-verifier-server
spec:
  affinity: {}
  resourceProtectionProfile: {}
  verifierConfig:
    verifyType: pgp # x509
    plugin:
    - name: helm
      enabled: false
    signPolicy:
      policies:
      - namespaces:
        - "*"
        signers:
        - "ClusterSigner"
        - "HelmClusterSigner"
      - scope: Cluster
        signers:
        - "ClusterSigner"
        - "HelmClusterSigner"
      signers:
      - name: "ClusterSigner"
        subjects:
        - commonName: "ClusterAdmin"
      - name: "HelmClusterSigner"
        subjects:
        - email: cluster_signer@signer.com
    ieResource: "apis.integrityverifier.io"
    ivAdminUserGroup: "system:masters,system:cluster-admins"
    ignore:
    - kind: Event
    - kind: Lease
    - kind: Endpoints
    - kind: TokenReview
    - kind: SubjectAccessReview
    - kind: SelfSubjectAccessReview
    patch:
      enabled: true
    log:
      consoleLog:
        enabled: true
        inScope:
        - kind: '*'
      contextLog:
        enabled: true
        inScope:
        - kind: '*'
      logLevel: trace
  verifierConfigCrName: iv-config
  globalConfig: 
    detectionMode: false
  imagePullSecrets: []
  certPoolConfig:
    createIfNotExist: false
    keyValue: test
    name: iv-certpool-secret
  keyRingConfig:
    createIfNotExist: false
    keyValue: test
    name: keyring-secret
  labels:
    app: iv-server
  logger:
    enabled: true
    es:
      enabled: false
      host: 10.200.10.10
      indexPrefix: ac-log
      port: 9200
      scheme: http
    http:
      enabled: false
      endpoint: http://sample-http-server:8093/api
    esSecretName: es-tls-certs
    image: iv-logging:local
    imagePullPolicy: IfNotPresent
    name: forwarder
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    stdOutput: true
  replicaCount: 1
  security:
    clusterRole: iv-cluster-role
    clusterRoleBinding: iv-cluster-role-binding
    podSecurityPolicyName: iv-psp
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000610000
    securityContextConstraintsName:  iv-scc
    serviceAccountName: iv-sa
    ivAdminSubjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:masters
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:cluster-admins
    autoIVAdminRoleCreationDisabled: false
  selector:
    app: iv-server
  server:
    chartBaseUrl: http://sample-chart-repo-server/charts
    contextLogEnabled: true
    verifierPolicyReloadSec: 10
    image: iv-server:local
    imagePullPolicy: IfNotPresent
    name: server
    port: 8443
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext: {}
  webhookConfigName: iv-webhook-config
  webhookServerTlsSecretName: iv-server-tls
  webhookServiceName: iv-server
  webhookNamespacedResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
  webhookClusterResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
    # OCP4.4 or earlier, need to select resources.
    # - podsecuritypolicies
    # - clusterrolebindings
    # - clusterroles
