apiVersion: apps/v1
kind: Deployment
metadata:
  name: ishield-observer
  namespace: integrity-shield-operator-system
spec:
  selector:
    matchLabels:
      app: ishield-observer
  template:
    metadata:
      labels:
        app: ishield-observer
    spec:
      restartPolicy: Always
      serviceAccountName: validator
      containers:
        # - command:
        #   - sleep
        #   - infinity
        - resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          name: observer
          env:
            - name: POD_NAMESPACE
              value: integrity-shield-operator-system
            - name: LOG_LEVEL
              value: info
            - name: REQUEST_HANDLER_CONFIG_KEY
              value: config.yaml
            - name: REQUEST_HANDLER_CONFIG_NAME
              value: request-handler-config
            - name: ENABLE_DETAIL_RESULT
              value: 'true'
            - name: ENABLE_PROVENANCE_RESULT
              value: 'true'
            - name: OBSERVER_RESULT_CONFIG_NAME
              value: verify-resource-result
            - name: OBSERVER_RESULT_CONFIG_KEY
              value: config.yaml
            - name: INTERVAL
              value: '5'
          imagePullPolicy: Always
          image: localhost:5000/integrity-shield-observer:0.2.5
          volumeMounts:
          - name: tmp
            mountPath: /tmp
      serviceAccount: validator
      volumes:
      - name: tmp
        emptyDir: {}
