apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: validator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ishield-sa-role
subjects:
- kind: ServiceAccount
  name: ishield-sa
  namespace: integrity-shield-operator-system