# permissions for end users to view integrityshields.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrityshield-viewer-role
rules:
- apiGroups:
  - apis.integrityshield.io
  resources:
  - integrityshields
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.integrityshield.io
  resources:
  - integrityshields/status
  verbs:
  - get
