//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/verifier/pkg/apis/verifierconfig/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/verifier/pkg/client/verifierconfig/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerifierConfigsGetter has a method to return a VerifierConfigInterface.
// A group's client should implement this interface.
type VerifierConfigsGetter interface {
	VerifierConfigs(namespace string) VerifierConfigInterface
}

// VerifierConfigInterface has methods to work with VerifierConfig resources.
type VerifierConfigInterface interface {
	Create(ctx context.Context, verifierConfig *v1alpha1.VerifierConfig, opts v1.CreateOptions) (*v1alpha1.VerifierConfig, error)
	Update(ctx context.Context, verifierConfig *v1alpha1.VerifierConfig, opts v1.UpdateOptions) (*v1alpha1.VerifierConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VerifierConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VerifierConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerifierConfig, err error)
	VerifierConfigExpansion
}

// verifierConfigs implements VerifierConfigInterface
type verifierConfigs struct {
	client rest.Interface
	ns     string
}

// newVerifierConfigs returns a VerifierConfigs
func newVerifierConfigs(c *ApisV1alpha1Client, namespace string) *verifierConfigs {
	return &verifierConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the verifierConfig, and returns the corresponding verifierConfig object, and an error if there is any.
func (c *verifierConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VerifierConfig, err error) {
	result = &v1alpha1.VerifierConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verifierconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VerifierConfigs that match those selectors.
func (c *verifierConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerifierConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VerifierConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verifierconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested verifierConfigs.
func (c *verifierConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("verifierconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a verifierConfig and creates it.  Returns the server's representation of the verifierConfig, and an error, if there is any.
func (c *verifierConfigs) Create(ctx context.Context, verifierConfig *v1alpha1.VerifierConfig, opts v1.CreateOptions) (result *v1alpha1.VerifierConfig, err error) {
	result = &v1alpha1.VerifierConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("verifierconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verifierConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a verifierConfig and updates it. Returns the server's representation of the verifierConfig, and an error, if there is any.
func (c *verifierConfigs) Update(ctx context.Context, verifierConfig *v1alpha1.VerifierConfig, opts v1.UpdateOptions) (result *v1alpha1.VerifierConfig, err error) {
	result = &v1alpha1.VerifierConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verifierconfigs").
		Name(verifierConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verifierConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the verifierConfig and deletes it. Returns an error if one occurs.
func (c *verifierConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verifierconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *verifierConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verifierconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched verifierConfig.
func (c *verifierConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerifierConfig, err error) {
	result = &v1alpha1.VerifierConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("verifierconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
