apiVersion: apis.integrityshield.io/v1alpha1
kind: IntegrityShield
metadata:
  name: integrity-shield-server
spec:
  namespace: integrity-shield-operator-system
  affinity: {}
  resourceSigningProfiles: []
  signerConfig: {}
  shieldConfig:
    plugin:
    - name: helm
      enabled: false
    iShieldAdminUserName: ""
    iShieldAdminUserGroup: "system:masters,system:cluster-admins"
    ignore:
    - kind: Event
    - kind: Lease
    - kind: Endpoints
    - kind: TokenReview
    - kind: SubjectAccessReview
    - kind: SelfSubjectAccessReview
    patch:
      enabled: true
    log:
      consoleLog:
        enabled: true
        inScope:
        - kind: '*'
      contextLog:
        enabled: true
        inScope:
        - kind: '*'
      logLevel: info
    sideEffect:
      createDenyEvent: true
      createIShieldResourceEvent: true
      updateRSPStatusForDeniedRequest: true
    sigstoreConfig:
      enabled: false
      rekorServerURL: ""
      useDefaultRootCert: true
      defaultRootCertURL: "https://raw.githubusercontent.com/sigstore/fulcio/main/config/ctfe/root.pem"
    imageVerificationConfig:
      enabled: false
      options: {}
  shieldConfigCrName: ishield-config
  imagePullSecrets: []
  globalConfig: 
    detectionMode: false
  certPoolConfigs:
  - createIfNotExist: false
    keyValue: test
    name: ishield-certpool-secret
  keyConfig: []
  labels:
    app: ishield-server
  logger:
    enabled: true
    es:
      enabled: false
      host: 10.200.10.10
      indexPrefix: ac-log
      port: 9200
      scheme: http
    http:
      enabled: false
      endpoint: http://sample-http-server:8093/api
    esSecretName: es-tls-certs
    image: quay.io/open-cluster-management/integrity-shield-logging:0.2.0
    imagePullPolicy: Always
    name: forwarder
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    stdOutput: true
  observer:
    enabled: false
    image: quay.io/open-cluster-management/integrity-shield-observer:0.2.0
    imagePullPolicy: Always
    name: observer
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  # inspector:
  #   enabled: false
  #   image: quay.io/open-cluster-management/integrity-shield-inspector:0.2.0
  #   imagePullPolicy: Always
  #   name: inspector
  #   resources:
  #     limits:
  #       cpu: 500m
  #       memory: 512Mi
  #     requests:
  #       cpu: 200m
  #       memory: 256Mi
  replicaCount: 1
  security:
    clusterRole: ishield-cluster-role
    clusterRoleBinding: ishield-cluster-role-binding
    podSecurityPolicyName: ishield-psp
    securityContextConstraintsName:  ishield-scc
    serviceAccountName: ishield-sa
    iShieldAdminSubjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:masters
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:cluster-admins
    autoIShieldAdminRoleCreationDisabled: false
  selector:
    app: ishield-server
  server:
    chartBaseUrl: http://sample-chart-repo-server/charts
    contextLogEnabled: true
    shieldPolicyReloadSec: 10
    image: quay.io/open-cluster-management/integrity-shield-server:0.2.0
    imagePullPolicy: Always
    name: server
    port: 8443
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext: {}
  api:
    contextLogEnabled: true
    shieldPolicyReloadSec: 10
    image: quay.io/open-cluster-management/integrity-shield-api:0.2.0
    imagePullPolicy: Always
    name: api
    serviceName: integrity-shield-api
    port: 8080
    servicePort: 8123
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext: {}
  controller:
    image: quay.io/open-cluster-management/integrity-shield-controller:0.2.0
    imagePullPolicy: Always
    name: controller
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  apiTlsSecretName: ishield-api-tls
  webhookConfigName: ishield-webhook-config
  webhookServerTlsSecretName: ishield-server-tls
  webhookServiceName: ishield-server
  webhookNamespacedResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
  webhookClusterResource:
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
    # OCP4.4 or earlier, need to select resources.
    # - podsecuritypolicies
    # - clusterrolebindings
    # - clusterroles
