//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/enforcepolicy/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/enforcepolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EnforcePoliciesGetter has a method to return a EnforcePolicyInterface.
// A group's client should implement this interface.
type EnforcePoliciesGetter interface {
	EnforcePolicies(namespace string) EnforcePolicyInterface
}

// EnforcePolicyInterface has methods to work with EnforcePolicy resources.
type EnforcePolicyInterface interface {
	Create(*v1alpha1.EnforcePolicy) (*v1alpha1.EnforcePolicy, error)
	Update(*v1alpha1.EnforcePolicy) (*v1alpha1.EnforcePolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EnforcePolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.EnforcePolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnforcePolicy, err error)
	EnforcePolicyExpansion
}

// enforcePolicies implements EnforcePolicyInterface
type enforcePolicies struct {
	client rest.Interface
	ns     string
}

// newEnforcePolicies returns a EnforcePolicies
func newEnforcePolicies(c *ResearchV1alpha1Client, namespace string) *enforcePolicies {
	return &enforcePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the enforcePolicy, and returns the corresponding enforcePolicy object, and an error if there is any.
func (c *enforcePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.EnforcePolicy, err error) {
	result = &v1alpha1.EnforcePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("enforcepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EnforcePolicies that match those selectors.
func (c *enforcePolicies) List(opts v1.ListOptions) (result *v1alpha1.EnforcePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EnforcePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("enforcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested enforcePolicies.
func (c *enforcePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("enforcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a enforcePolicy and creates it.  Returns the server's representation of the enforcePolicy, and an error, if there is any.
func (c *enforcePolicies) Create(enforcePolicy *v1alpha1.EnforcePolicy) (result *v1alpha1.EnforcePolicy, err error) {
	result = &v1alpha1.EnforcePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("enforcepolicies").
		Body(enforcePolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a enforcePolicy and updates it. Returns the server's representation of the enforcePolicy, and an error, if there is any.
func (c *enforcePolicies) Update(enforcePolicy *v1alpha1.EnforcePolicy) (result *v1alpha1.EnforcePolicy, err error) {
	result = &v1alpha1.EnforcePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("enforcepolicies").
		Name(enforcePolicy.Name).
		Body(enforcePolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the enforcePolicy and deletes it. Returns an error if one occurs.
func (c *enforcePolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("enforcepolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *enforcePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("enforcepolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched enforcePolicy.
func (c *enforcePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnforcePolicy, err error) {
	result = &v1alpha1.EnforcePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("enforcepolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
