//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/inspector/pkg/apis/protectedresourceintegrity/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/inspector/pkg/client/protectedresourceintegrity/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProtectedResourceIntegritiesGetter has a method to return a ProtectedResourceIntegrityInterface.
// A group's client should implement this interface.
type ProtectedResourceIntegritiesGetter interface {
	ProtectedResourceIntegrities(namespace string) ProtectedResourceIntegrityInterface
}

// ProtectedResourceIntegrityInterface has methods to work with ProtectedResourceIntegrity resources.
type ProtectedResourceIntegrityInterface interface {
	Create(ctx context.Context, protectedResourceIntegrity *v1alpha1.ProtectedResourceIntegrity, opts v1.CreateOptions) (*v1alpha1.ProtectedResourceIntegrity, error)
	Update(ctx context.Context, protectedResourceIntegrity *v1alpha1.ProtectedResourceIntegrity, opts v1.UpdateOptions) (*v1alpha1.ProtectedResourceIntegrity, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ProtectedResourceIntegrity, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ProtectedResourceIntegrityList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProtectedResourceIntegrity, err error)
	ProtectedResourceIntegrityExpansion
}

// protectedResourceIntegrities implements ProtectedResourceIntegrityInterface
type protectedResourceIntegrities struct {
	client rest.Interface
	ns     string
}

// newProtectedResourceIntegrities returns a ProtectedResourceIntegrities
func newProtectedResourceIntegrities(c *ApisV1alpha1Client, namespace string) *protectedResourceIntegrities {
	return &protectedResourceIntegrities{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the protectedResourceIntegrity, and returns the corresponding protectedResourceIntegrity object, and an error if there is any.
func (c *protectedResourceIntegrities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProtectedResourceIntegrity, err error) {
	result = &v1alpha1.ProtectedResourceIntegrity{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProtectedResourceIntegrities that match those selectors.
func (c *protectedResourceIntegrities) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProtectedResourceIntegrityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ProtectedResourceIntegrityList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested protectedResourceIntegrities.
func (c *protectedResourceIntegrities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a protectedResourceIntegrity and creates it.  Returns the server's representation of the protectedResourceIntegrity, and an error, if there is any.
func (c *protectedResourceIntegrities) Create(ctx context.Context, protectedResourceIntegrity *v1alpha1.ProtectedResourceIntegrity, opts v1.CreateOptions) (result *v1alpha1.ProtectedResourceIntegrity, err error) {
	result = &v1alpha1.ProtectedResourceIntegrity{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(protectedResourceIntegrity).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a protectedResourceIntegrity and updates it. Returns the server's representation of the protectedResourceIntegrity, and an error, if there is any.
func (c *protectedResourceIntegrities) Update(ctx context.Context, protectedResourceIntegrity *v1alpha1.ProtectedResourceIntegrity, opts v1.UpdateOptions) (result *v1alpha1.ProtectedResourceIntegrity, err error) {
	result = &v1alpha1.ProtectedResourceIntegrity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		Name(protectedResourceIntegrity.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(protectedResourceIntegrity).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the protectedResourceIntegrity and deletes it. Returns an error if one occurs.
func (c *protectedResourceIntegrities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *protectedResourceIntegrities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched protectedResourceIntegrity.
func (c *protectedResourceIntegrities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProtectedResourceIntegrity, err error) {
	result = &v1alpha1.ProtectedResourceIntegrity{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("protectedresourceintegrities").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
