//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/IBM/integrity-enforcer/enforcer/pkg/apis/resourcesignature/v1alpha1"
	scheme "github.com/IBM/integrity-enforcer/enforcer/pkg/client/resourcesignature/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceSignaturesGetter has a method to return a ResourceSignatureInterface.
// A group's client should implement this interface.
type ResourceSignaturesGetter interface {
	ResourceSignatures(namespace string) ResourceSignatureInterface
}

// ResourceSignatureInterface has methods to work with ResourceSignature resources.
type ResourceSignatureInterface interface {
	Create(*v1alpha1.ResourceSignature) (*v1alpha1.ResourceSignature, error)
	Update(*v1alpha1.ResourceSignature) (*v1alpha1.ResourceSignature, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourceSignature, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourceSignatureList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceSignature, err error)
	ResourceSignatureExpansion
}

// resourceSignatures implements ResourceSignatureInterface
type resourceSignatures struct {
	client rest.Interface
	ns     string
}

// newResourceSignatures returns a ResourceSignatures
func newResourceSignatures(c *ResearchV1alpha1Client, namespace string) *resourceSignatures {
	return &resourceSignatures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceSignature, and returns the corresponding resourceSignature object, and an error if there is any.
func (c *resourceSignatures) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceSignature, err error) {
	result = &v1alpha1.ResourceSignature{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcesignatures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceSignatures that match those selectors.
func (c *resourceSignatures) List(opts v1.ListOptions) (result *v1alpha1.ResourceSignatureList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ResourceSignatureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcesignatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceSignatures.
func (c *resourceSignatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcesignatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a resourceSignature and creates it.  Returns the server's representation of the resourceSignature, and an error, if there is any.
func (c *resourceSignatures) Create(resourceSignature *v1alpha1.ResourceSignature) (result *v1alpha1.ResourceSignature, err error) {
	result = &v1alpha1.ResourceSignature{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcesignatures").
		Body(resourceSignature).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceSignature and updates it. Returns the server's representation of the resourceSignature, and an error, if there is any.
func (c *resourceSignatures) Update(resourceSignature *v1alpha1.ResourceSignature) (result *v1alpha1.ResourceSignature, err error) {
	result = &v1alpha1.ResourceSignature{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcesignatures").
		Name(resourceSignature.Name).
		Body(resourceSignature).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceSignature and deletes it. Returns an error if one occurs.
func (c *resourceSignatures) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcesignatures").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceSignatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcesignatures").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceSignature.
func (c *resourceSignatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceSignature, err error) {
	result = &v1alpha1.ResourceSignature{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcesignatures").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
