kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signservice-operator
subjects:
- kind: ServiceAccount
  name: signservice-operator
  namespace: integrity-enforcer-ns
roleRef:
  kind: ClusterRole
  name: signservice-operator
  apiGroup: rbac.authorization.k8s.io
